### ISSUE TITLE
ParagraphVectors with same content but different labels produces different vectors

### ISSUE THREAD

**Issue by rohanar** [deeplearning4j/deeplearning4j#1129]
Main Class: https://gist.github.com/rohanar/5ee3d6abd4f50717f5a3
Iterator: https://gist.github.com/rohanar/73e5a2b2ee47e23ccb51

Output of MYDOC_1 and MYDOC_2 ParagraphVectors:

Vector of MYDOC_1: 0.05128706619143486 0.023959333077073097 -0.06078672036528587 0.032672032713890076 -0.04448729380965233 0.05854293331503868 0.06542444974184036 0.04277518764138222 -0.06504464149475098 -0.01807497628033161 

Vector of MYDOC_2: 0.08950962871313095 0.028198037296533585 -0.08588799089193344 -0.00515331793576479 0.016811901703476906 0.013588040135800838 0.0575483962893486 0.011253135278820992 -0.004862723406404257 0.023988481611013412

**Comment by rohanar** [comment]
Please note: The only difference to the original ParagraphVector example is the use of a custom Iterator to assign lables.

**Comment by raver119** [comment]
This is not a bug, but a consequence of initial random initialization + small training corpus.

Within ParagraphVectors each "label" is just another word, whose context is the whole content of document/paragraph/sentence. But since both of your "labels" are random-initialized, they will never become "equal". They will have equal context applied, but due to random initialization they will be as close as possible, but not equal. 0.8, 0.9, or even 0.99 in ideal world with ideal corpus and ideal params, but never 1.0.
