### ISSUE TITLE
Updating the tutorial for hardware acceleration under windows.

### ISSUE THREAD

**Issue by MSEK2015** [deeplearning4j/deeplearning4j#1168]
Hello DL4J-Team,

I started to install DL4J two days ago and was confused about the BLAS-error message. 

My problems were to understand what BLAS is and what netlib-java is. I'm coding under Windows 10 64-Bit with IntelliJ.

Following: 
- Quickstart http://deeplearning4j.org/quickstart (worked fine), but I wondered why I should check the POM file separately, the one in the git repository should be the newest.
- Then I got the BLAS error, leading me to http://deeplearning4j.org/gettingstarted with the short paragraph:

> For OpenBlas (see below) on Windows, download this file. Extract to somewhere such as C:/BLAS. Add that directory to your system’s PATH environment variable.

However, this is not enough and will not fit to every system. I also assume that the files contained are not up to date and not compatible with 64-bit. It is good that you provide information about manually compiling BLAS with MinGW but most Windows users (like me) are too lazy to install such additional tools and we except everything to work out of the box (since the first steps are used to evaluate the usability of DL4J for your personal projects).

I found this very helpful page http://blog.csdn.net/oncealong/article/details/50068831 (need to translate it) where JNI and the DLLs dependencies are explained. 

With the files provided https://www.dropbox.com/s/6p8yn3fcf230rxy/ND4J_Win64_OpenBLAS-v0.2.14.zip?dl=1 I got a LinkageError in java which might also rely on the fact that netlib-native_system-win-x86_64.dll is missing in the provided package. 

So after debugging and understanding the code, I did these steps to use the BLAS hardware acceleration:

- Downloaded Netlib's native DLL (http://mvnrepository.com/artifact/com.github.fommil.netlib/netlib-native_system-win-x86_64/1.1) in version 1.1 
- renamed it to "netlib-native_system-win-x86_64.dll" since this name is expected by the DL4J framework
- Downloaded OpenBlas for my 64-Bit System (https://sourceforge.net/projects/openblas/files/v0.2.15/)
- Took the libopenblas.dll (Version 2.15) from the bin folder in the archive and did two copies (liblapack3.dll and libblas3.dll) like it has been described in several tutorials online and in the link above.   
- Took the fortran, gcc and quadmath DLLs from your package 

All these files I copied to the /bin folder of my JDK 8 (64-Bit as well!) and everythink worked like a charme. 

Obviously I could copy these DLLs also in defined Windows PATH variable but JDK's /bin folder is the first to be looked up by Java's "System.load()".

I hope this is helpful for someone else.

Best regards,
Sebastian

**Comment by chrisvnicholson** [comment]
Thanks, MSEK2015. We'll see where we can weave your tips into our docs.

**Comment by AlexDBlack** [comment]
Thanks for posting this @MSEK2015

First, just fyi, we'll be retiring nd4j-x86 backend as of 3.9 (next release). We're finding netlib-java has too high an overhead (due to copying being required on the JNI calls), so we're switching how we link to native BLAS; already seeing decent performance improvements on matrix multiplication ops from that. In theory, this may make it a little easier for users to set up native blas, too.

"I also assume that the files contained are not up to date and not compatible with 64-bit." It's the 0.2.14 precompiled version for openblas, and definitely is the 64-bit version. Not the latest (which is 0.2.15), but pretty close.

Not sure why you need to mess with the netlib-native DLLs. They are bundled with netlib-java, and hence should already be available. For example, I've got a netlib-native_system-win-x86_64.dll in the following jar file (i.e., in local maven files):
C:\Users\Alex\.m2\repository\com\github\fommil\netlib\netlib-native_system-win-x86_64\1.1\netlib-native_system-win-x86_64-1.1-natives.jar
The only thing I can assume is some platform-specific compatability issue, or perhaps that isn't on (class)path for some reason. Good to know that this might help, in spite of what *should* be occurring.

Anyway, what I'm suggesting is that we leave this issue open here for reference until 3.9 comes out, and link to this from the docs. We'll need to rewrite that section of the docs then, at which point we can decide how much of this info to keep.

**Comment by agibsonccc** [comment]
We've  moved to libnd4j. This won't be relevant anymore
