### ISSUE TITLE
Spark verison of DNN configuration with inputPreProcessor parameter throws jackson error

### ISSUE THREAD

**Issue by ramsrivatsa** [deeplearning4j/deeplearning4j#1191]
when including `.inputPreProcessor(0, new RnnToCnnPreProcessor(100, 100, 3))` in any DNN configuration file with spark, jackson error is thrown. using latest stable version of spark, dl4j, nd4j and version 2.5.1 or jackson.

**Comment by AlexDBlack** [comment]
Thanks for reporting this. This was an error in 0.4-rc3.8, due to lack of JSON subtypes information for that preprocessor (and CnnToRnnPreProcessor too). It has been fixed already here: https://github.com/deeplearning4j/deeplearning4j/commit/a6f693ddd8f24b4ed3596938c6c532bc76562657#diff-34105347d24c7ceacc151f665c0f5e65
