### ISSUE TITLE
Computation graph: Selecting a subset of the input

### ISSUE THREAD

**Issue by rubenfiszel** [deeplearning4j/deeplearning4j#1197]
I would like to select a subset of an input/output based on a rule that filter the columns based on their positions (like only the column < y or only the columns divisible by z) and create a new input. 

It's a sort of TransformationVertex.

By exemple I would like my input to be splitted in 3 and each parts send to a different Vertex. I could have a data made of 3 separate inputs but it would be much less modular.

**Comment by AlexDBlack** [comment]
Subset vertex (as described here: http://deeplearning4j.org/compgraph#vertextypes) currently only allows you to do a range of activations. So, columns in an interval [a,b].
For activations out of a layer, there's nothing special about them or the order (due to random weight init), so interval is fine. Only case where order matters is doing a subset of the original input array.

Regarding input subsets, RecordReaderMultiDataSetIterator can do intervals out of a record reader: http://deeplearning4j.org/compgraph#rrmdsi1

As for other subset rules, we don't currently have subsetting based on columns divisible by Z (i.e., every Zth activation). This wouldn't be too hard to add, if you really need it.
