### ISSUE TITLE
Evaluation object reporting wrong counts for TP, FP, TN, FN

### ISSUE THREAD

**Issue by Habitats** [deeplearning4j/deeplearning4j#1230]
For a binary classification with two outputs, eihter `[1,0]` or `[0,1]`, the following outputs are generated from the `Evalution` object:

```
The following confusion matrix:
                  Predicted Class
                       0     1 Total
Actual Class     0  1500     2  1502
                 1    68   131   199
             Total  1568   133
             
And the following counts:
    TP     FP     FN     TN 
  1631     70     70   1631 
  
i.e. --> TP == TN == (confusionTP + confusionTN) and FN == FP == (confusionFP + confusionFN)
```

The relevant lines in `Evaluation` are 138-168, in the `eval()` method. The method increments two counters for every given example, when it really should be incrementing _one _of them. 

Problem is present both in 3.8 and 3.9-SNAPSHOT.

**Comment by AlexDBlack** [comment]
Referring to this: http://scikit-learn.org/stable/modules/model_evaluation.html
"In extending a binary metric to multiclass or multilabel problems, the data is treated as a collection of binary problems, one for each class. There are then a number of ways to average binary metric calculations across the set of classes, each of which may be useful in some scenario."

So yes, the values returned by the truePositives() and trueNegatives() etc methods are wrong, in so far as they return the sum of truePositives/negatives/etc for all classes.

The problem here is that in the multiclass classification, there is no single true/false positive/negative values - these binary metrics are only defined *for each class* not for the classification problem as a whole. I'm thinking that having truePositives()/trueNegatives()/etc methods that return a double doesn't make sense in the context of multiclass classification. Perhaps instead these methods should return true positives/negatives of the binary problems per class (i.e., a list or map).

Now, for binary it *does* make sense to return a double, so the alternative is to make these methods a special case for binary only (I don't really like this, but perhaps it'd be fine if we threw an exception for non-binary evaluation). However we also have the issue of deciding which (0 or 1) is the positive class? (Do we hard-code this to class 0 by conversion?)

**Comment by Habitats** [comment]
> Perhaps instead these methods should return true positives/negatives of the binary problems per class (i.e., a list or map).

I think this is the most sensible solution. This information is already present in the confusio matrix, but at the moment they need to be extracted manually. 

Also, why are these methods even returning doubles in the first place? In which scenario are they something other than discrete counts?

**Comment by AlexDBlack** [comment]
Right. They are discrete counts, so double doesn't make sense even in the binary case (int does though).
I'll change those truePositive()/Negative()/etc methods to return a map instead.

**Comment by Habitats** [comment]
That would be neat!

**Comment by Habitats** [comment]
Any timeframe, btw?
