### ISSUE TITLE
"Length is >= Integer.MAX_VALUE" error when images given to CNN are larger than 500x500

### ISSUE THREAD

**Issue by justineyster** [deeplearning4j/deeplearning4j#1791]
I'm working on a deep learning problem with images on a CNN. I can resize my input images to whatever size I specify, and everything works fine if this size is relatively small. However, I get a strange error during training when I try to run the CNN with images larger than 500x500 pixels: "java.IllegalArgumentException: Length is >= Integer.MAX_VALUE: lengthLong() must be called instead."

Stack trace: https://gist.github.com/justineyster/081ef354bd4756a0ecd4476f45326d35

CNN code: https://gist.github.com/justineyster/e644be162dc83046f8537d864e19e708

**Comment by AlexDBlack** [comment]
At a guess: the im2col array is larger than 2.1 billion (Integer.MAX_VALUE) elements.

For first conv layer: (600-5+0)/1+1 = 596 image patches in each dimension, of size 5x5
Total array, with 50 examples, depth 3 input: (596x596x(5x5)x3x50) = 1.33 billion elements.
So that should be OK, unless I've messed up the math there.

FWIW 1.33 billion floats is over 5.3GB. So though we do need to fix this, your network training is going to be slow and take up a huge amount of memory, with those settings.
You can also reduce the batch size to (probably) fix that error + reduce memory

**Comment by Goldado** [comment]
@AlexDBlack The math seems right, and with 32bit floats it's around 4.95 GigaBytes. @justineyster needs to make sure he has enough free ram for that (you probably need at least a 8GB ram on your machine). Though if I were you I would make sure that I actually need the colors in the input and maybe even resize the images.
