### ISSUE TITLE
backpropGradient throws mismatched len exception in ComputationGraph

### ISSUE THREAD

**Issue by FelixVoelker** [deeplearning4j/deeplearning4j#2004]
A ComputationGraph with an incorporated ConvNet throws an mismatched len exception when calculating the backpropGradient for an external error. 

https://gist.github.com/FelixVoelker/725734065b992142aff1083b48408a9f

-> Problem lies most likely in the "output" layer where the ConvNet gets connected with a feedforward Layer.
-> output function does not throw an exception

**Comment by AlexDBlack** [comment]
So there's two issues.
First, as of 0.5.0 ComputationGraph wasn't properly setting nIns for CNN layers: that has been fixed here.
https://github.com/deeplearning4j/deeplearning4j/issues/1934

Second: because of that, setting nIns is necessary, but your configuration isn't setting them correctly.

The following configuration works on 0.5.0: (note the nIn on the dense layer is unnecessary - the correct value is 150, from h=5, w=3, d=10 activations out of c2)
```java
        ComputationGraphConfiguration builder1 = new NeuralNetConfiguration.Builder()
            .seed(System.currentTimeMillis())
            .iterations(1)
            .learningRate(0.0001)
            .weightInit(WeightInit.XAVIER)
            .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
            .updater(Updater.NESTEROVS).momentum(0.01)
            .graphBuilder()
            .addInputs("in1")
            .setInputTypes(InputType.convolutional(10,3,1))
            .addLayer("C0", new ConvolutionLayer.Builder(3,1).stride(1,1).nIn(1).nOut(10).build(), "in1")
            .addLayer("C1", new ConvolutionLayer.Builder(3,1).stride(1,1).nIn(10).nOut(10).build(), "C0")
            .addLayer("C2", new ConvolutionLayer.Builder(2,1).stride(1,1).nIn(10).nOut(10).build(), "C1")
            .addLayer("output", new DenseLayer.Builder().nOut(1).activation("identity").build(), "C2")
            .setOutputs("output")
            .build();

        ComputationGraph network = new ComputationGraph(builder1);
        network.init();

        INDArray in1 = Nd4j.rand(new int[]{1,1,10,3});
        INDArray[] output = network.output(in1);
        System.out.println(output[0]);
        Gradient backpropGradient = network.backpropGradient(Nd4j.create(new float[]{-1}));
        System.out.println("Test");
```

As of dl4j master, you can use the same config without any nIn values.
