### ISSUE TITLE
Manual memory management options

### ISSUE THREAD

**Issue by jfolt** [deeplearning4j/deeplearning4j#2057]
This is an idea for a feature request - provide (advanced) API for some manual memory management options:
1. allow selecting where INDArary's memory is allocated (GPU or CPU)
2. allow manually move INDArray between CPU/GPU (or between GPU/GPU)
3. tell me where the NDArray is currently stored (e.g. which GPU)

Option #1 - for ability to store some NDArrays on CPU memory (while also training on GPU). For example, to preload a large dataset into CPU memory (which is too large to store on GPU and too slow to load dynamically).

Option #3 primarily for debugging.

Recently I run into a memory problem with Video classification example. No matter what I did, I was not able to run it fully on GPU (on CPU it works fine), it was failing in second epoch due to memory problems (even when CPU java heap size was set to 12GB and GPU memory was 4GB).

I imagine a problem like that could be easily solved using proposed option #1 and #2 - I could simply move current dataset NDArray to/from CPU/GPU before/after each net.fit(DataSet). That would allow me to train very large datasets, limited only by the size of minibatch.

**Comment by raver119** [comment]
question 1) is actually worth considering, especially since Xeon Phi's are coming.

question 2) I'm not ready to answer is it worth adding or not. Obviously it's possible to add, but it might lead to bad CUDA practices. I should think more about it, sorry.

question 3 is possible right now, but it will make your code incompatible with nd4j-native backend, since it will be using CUDA backend-specific methods.

**Comment by jfolt** [comment]
More thoughts about it:

For #1. A work around would be to use java arrays or other math library for all operations which should run on CPU, and use NDArray only for GPU operations. We would lose the advantages of DL4j on CPU in this case (for example all iterators etc would have to be created differently). Not clean. Not very easy but possible.

For #2, I could create one NDArray DataSet and populate it from java heap memory buffer before it should execute on GPU. But this is only fine for 1 GPU. I couldn't (?) do this with 2 (or more) GPUs (decide where to process my DataSet). I don't like when something is not possible :-).

**Comment by raver119** [comment]
#2 - i hadn't said it's impossible. It IS possible, and even right now. But if i'll expose that to public, i'll start getting complaints about speed, because context/device switches are expensive, and will bring 100500 synchronization issue. So i have to think carefully & thoroughly about proper exposure there, in a way which won't create problems in future.

**Comment by raver119** [comment]
#1 - that's actually more about hybrid operations. That's something we want to have, but we still don't have that option.

**Comment by agibsonccc** [comment]
I have to disagree with this. I think it should stay managed. We started
this project in the first place because literally everyone else was doing
it wrong :(.
