### ISSUE TITLE
GPU performance does not get the target performance.

### ISSUE THREAD

**Issue by welcomealcol** [deeplearning4j/deeplearning4j#2130]
Hello, I ran the example \MultiGpuLenetMnistExample.java, and got the time about 150 seconds. And the related LenetMnistExample.java, got about 210 seconds. My GPU card is GTX1080. The performance improvement could not be little like that. I tried to set a larger MaximumDeviceCache from 2G to 4G. Seems not work well also. Can I have another way to improve the performance? Many Thanks

CPU: Xeon (R) E3-1231 v3 @3.40Ghz 3.40Ghz
Memory: 32Gb
Win7 64 bit
GPU: GTX 1080

**Comment by raver119** [comment]
Technically there should be no improvement, because you have only 1 gpu. So you get this improvement only because lenet example is small one, and it's unable to fill GPU with enough job in current TAD model.

Reason i've asked to file an issue, is surprisingly low performance for single-threaded Lenet example. My 1070 is faster, almost twice faster. And i want to investigate this.

**Comment by raver119** [comment]
Surprisingly confirming issue. Under linux current CUDA code is significantly faster, without ANY changes:

That's my time under linux: https://gist.github.com/raver119/d0918c9b042f840df8eced2bb51ed106
Windows time will be posted later, but it's somewhere around 25-30% slower.

**Comment by raver119** [comment]
This issue should be fixed on current master.
