### ISSUE TITLE
Integrate new nd4j-parameter-server in to spark training and parallelwrapper

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#2193]
With the new parameter server module in nd4j, we don't have to reply on spark for communication.

As we know spark is terrible at binary communication and sending vectors over a network efficiently.
It's also hard to do simple things like async training without this.

This should be configurable behavior that allows for the old school spark communication we currently have while also allowing us to communicate using aeron.

The main reason a user may want to disable this is due to the daemons that need to be started for each worker jvm as well as the communication on the master.

Yet to do yet is benchmarking the parameter server .

Main thing we need to do now is integrate the existing jvm  management the parameter server  already has.

We can see how to do this in the nd4j parameter server tests.

**Comment by dgreco** [comment]
I wonder if this communication layer could be pluggable. I think that being able to support high speed/low latency protocol like infiniband maybe masked by a MPI library. Thais would allow the usage of dl4j in a more HPC oriented cluster.

**Comment by agibsonccc** [comment]
We intend that:
http://highscalability.com/blog/2014/11/17/aeron-do-we-really-need-another-messaging-system.html

Ctrl + f infiniband. Aeron is just a protocol. We inend on working on HPC clusters as well. This is also a big reason why we use javacpp:
https://github.com/bytedeco/javacpp

Easy interop with libraries like that. Aeron itself being a protocol is a great start to that though.

**Comment by dgreco** [comment]
Cool!

**Comment by huitseeker** [comment]
Note : I do believe you can retrofit Spark for sparse model updates, using e.g. just [indexedRDD](https://github.com/amplab/spark-indexedrdd) or a [semi-persistent](https://www.lri.fr/~conchon/publis/spds-esop08.pdf) version of it.

The daemons proliferation is indeed problematic, and tbh Spark already has this issue itself since the [shuffle service](https://issues.apache.org/jira/browse/SPARK-3796). It has been my experience that in large installations, the added complexity of deployment tends to be a showstopper so that I would loathe the dependency on the parameter server. It's what lagom, or the tooling suite around Mesos are fighting so hard to solve. 

OTOH I'm fine with the parameter server being one of several backends accessed through a proper interface.

Finally, it may be that some form of asynchronicity can be retro-fitted into Spark, e.g. by relying on [AsynchronousRDDActions](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.rdd.AsyncRDDActions).

**Comment by agibsonccc** [comment]
One of my main problems is flexibility. It's a lot harder to do things like async updates and push/pull in a simple map function. No deep learning implementation has this stuff implemented like how spark would do it. There's also different hardware requirements. Spark also isn't going to go down in to rdma/infiniband.

My other problem is any of this stuff going in to rdds. That inherently means on heap memory.

The async stuff might be interesting - but half my problem is coupling any of that to spark at all.

**Comment by huitseeker** [comment]
Just checking : are you aware of the off-heap memory storage and of 
https://issues.apache.org/jira/browse/SPARK-10399 ?

**Comment by agibsonccc** [comment]
That's great and all but there's still going to be managing GPU memory. This won't handle that case either. We have our own separate memory management for that as well. Controlling the parameter server allows us to make optimizations ourselves specific to different kinds of hardware setups.

**Comment by agibsonccc** [comment]
This is done.
