### ISSUE TITLE
NumberFormatException while running WordVectorSerializer.readWord2Vec

### ISSUE THREAD

**Issue by dkincaid** [deeplearning4j/deeplearning4j#2236]
While trying to read in a word2vec model that I previously saved using `writeWord2Vec` I am getting a `NumberFormatException`. Using version 0.6.0. The full model file is 1.6GB (compressed), so would be difficult to share. What other information could I provide or should I look at to troubleshoot?

Here's the relevant info from the stack trace:

```
NumberFormatException.java:   65  java.lang.NumberFormatException/forInputString
              Integer.java:  592  java.lang.Integer/parseInt
              Integer.java:  615  java.lang.Integer/parseInt
 WordVectorSerializer.java:  849  org.deeplearning4j.models.embeddings.loader.WordVectorSerializer/readWord2VecFromText
 WordVectorSerializer.java:  785  org.deeplearning4j.models.embeddings.loader.WordVectorSerializer/readWord2Vec
```

**Comment by raver119** [comment]
This is probably known issue, and already fixed in current master.
Probably there's words with whitespaces got saved within model, so only workaround solution for now it to parse them line by line and apply some replacement for whitespaces.

Sorry :(

On current master it's already fixed with forced base64 encoding during save/load of models.

**Comment by dkincaid** [comment]
Ok. Do you know when you'll be releasing this code to Maven central? I've tried building it myself, but can't get ND4J to build therefore deeplearning4j won't build either.

**Comment by raver119** [comment]
As soon as UI overhaul finishes.
