### ISSUE TITLE
Scala version build script not working correctly

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2285]
+++ Step 1 +++
Set DL4J to 2.10 using ./change-scala-versions.sh 2.10
-> Dependency tree is good: only 2.10, no 2.11 dependencies
Install DL4J (just 2.10 - using "mvn clean install -DskipTests")
Use dl4j-spark_2.10 in a minimal project: dependency tree is good - only 2.10 dependencies
No problems so far.

+++ Step 2 +++
Set DL4J to 2.11 using ./change-scala-versions.sh 2.11
-> DL4J dependency tree: only 2.11, no 2.10 deps
Install DL4J (just 2.11 - using "mvn clean install -DskipTests")
-> Check local maven repo: dl4j-spark_2.10 files (jars, poms) have NOT been modified since 2.10 install. 2.10 pom in maven repo has only 2.10 deps
Check dependency tree for minimal project still using dl4j-spark_2.10:
dl4j-spark_2.10 now includes BOTH spark 2.10 and 2.11 (and mllib 2.10 and 2.11) as direct dependencies of dl4j-spark_2.10 (not transitive)

Confirmed as occurring on master and ab_ui branches.

**Comment by saudet** [comment]
I've confirmed that the problem comes from this file:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/pom.xml
The version of the spark dependencies are changed, but the artifactId isn't changed and ends up overwriting the information about the other version in the repository.

**Comment by saudet** [comment]
Similar but less serious issue with this one too:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark-parameterserver/pom.xml

**Comment by huitseeker** [comment]
At the end of the day, when you publish :
- a scala-dependent artifact foo
- that other modules (e.g. bar) may depend on,
You need to also annotate foo's artifactid  (not just the artifactid of its dependencies) with the used binary scala version. Otherwise, that scala version gets pulled on your classpath transitively, because there's inherently two versions of foo, and because the build of bar for e.g. 2.10 pulls in the freshest, which can be the foo built on 2.11

Four solutions :
- use a scala-aware tool like sbt (pros : works seamlessly, incl publish cons : unfamiliar with sbt)
- use a bash script that also mangles hardcoded annotations to artifactIds, on top of the existing scala.binary.version property mangling (pros : works, cons : regexp script can be prone to error, adding a new scala-dependent module complex)
- do the above but use two branches for building, one for 2.10, one for 2.11, each hardcoding distinct annotated artifactIds (pros : works, need for a conscious commit kinda mitigates the risk of breakage of the above, cons : merge operations at build publication)
- use a bash script that mangles just the scala.binary.version, and then recall that property in the artifactId, in the fashion of ScalNet's pom (pros: the closest to what we have now cons: deprecated, breaks other tools)

**Comment by AlexDBlack** [comment]
The parameter server one is just wrong, given it has direct dependency on scala version.

But you are saying we also need to do the following too:
org.deeplearning4j <artifactId>spark</artifactId> -> <artifactId>spark_2.10</artifactId>?

FYI this is what we do currently - which is basically your second solution
https://github.com/deeplearning4j/deeplearning4j/blob/master/buildmultiplescalaversions.sh
https://github.com/deeplearning4j/deeplearning4j/blob/master/change-scala-versions.sh
