### ISSUE TITLE
UI throws errors before receiving session data

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#2344]
When the UI is first booted up, it throws NPEs since data for an existing session has not yet been initialized. See gist: https://gist.github.com/crockpotveggies/420755d5e0b28be700fa8bbfe66a4d0d

**Comment by AlexDBlack** [comment]
I haven't been able to reproduce this locally, but I'm pretty sure it's due to static/initialization info having been posted, but no update (i.e., network) information being available. That's the only thing that makes sense given the exception, line number, and the fact that it occurs only at the very start of training.

Assuming that is the case, it is fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2343
