### ISSUE TITLE
Add description for filing issues

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#2414]
Right now we don't really have a defined format for filing issues it would be good to have a defined format so people don't have to look at other github issues to understand the formatting.

**Comment by huitseeker** [comment]
See also https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by huitseeker** [comment]
Fixed by
https://github.com/deeplearning4j/rl4j/pull/29
https://github.com/deeplearning4j/Arbiter/pull/75
https://github.com/deeplearning4j/dl4j-examples/pull/429
https://github.com/deeplearning4j/nd4j/pull/1738
https://github.com/deeplearning4j/DataVec/pull/225
https://github.com/deeplearning4j/deeplearning4j/pull/3149
