### ISSUE TITLE
Plans for 0.8.0

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#2422]
DL4j:
- DeepWalk impl migration to SequenceVectors, to benefit from latest native aggregations performance improvements
- SequenceVectors implementation for Spark: Word2Vec/ParagraphVectors/Glove/DeepWalk
- AsyncDataSetIterator migration to terminator-based implementation

ND4j:
- ~~~Built-in profiler for easier performance issues investigation.~~~ 
- JVM GC workaround 
- HALF2 datatype for CUDA

**Comment by mjakobus** [comment]
@raver119 
Regarding the JVM GC workaround. Would it be possible that in the course of this memory management rewrite a new AllocationModel could be added? Something like AllocationModel.MANUAL?
I know, that the main goal of dl4j is a managed memory system, but in some cases more control over the current allocations in vram would be very helpful. 

For example: I have a certain point in my program where I exactly know which DataSets and which MultiLayerNetwork I currently need and after training/evaluation I exactly know when I don't need them anymore, at this point I would like to unbind them from the vram and load the next DataSet and MultiLayerNetwork (I'm doing 10 fold crossvalidation).

In general it would be really useful especially for smaller data use cases. For training with images 8GB vram isn't very much and the user can be happy that the memory management is done for him, but for training with business data (in my case for warehouse optimization [~20000 vectors with 300 features]) in 8GB vram is a lot of space for business data... Often enough space for *all* data. I already tested using dl4j when all data is in memory (by preloading the mini batches as DataSets in a List). I feels like flying with Warp 10. Without preloading the performance is not comparable, even when using the AsyncDataSetIterator.

The problem with the preloaded DataSets is that with the 10 fold crossvalidation I have for the first folds a device hit ratio of 99% but for the last folds it shrinks to around 40% and thus also the performance decreases. Using AllocationModel.DIRECT I saw, that every fold is just using 2GB at maximum, so there should be enough place, because there is only one fold at a time in memory.

The AllocationModel.DIRECT is already going in the right direction for me, but it seems, that is freeing up the resources to aggressively.  
Btw. I also saw already other users asking for such a mechanism so there is definitely an interest for such thing.

Sorry for the long post ;)

**Comment by raver119** [comment]
Problem itself actually is not in DataSets and/or their preload/cache/allocation/whatever. It's about generic op invocation mechanic and memory use for those ops. I.e. consider this code:

```
public void method() {
   ...
   INDArray Z = X.mul(Y);
  ...
}
```

At some moment of time X.mul(Y) will be executed, and there will be memory allocated for Z. Then, some time later, memory should  be released. Wen method() call happens in cycle, you'll end up allocating Z over and over, and such allocation isn't "free" call. 

That's why we use cache for memory, and that's why we're going to change allocation process soon.
It's not about preload. It's about malloc/free effectiveness together with JVM GC reliance.

**Comment by agibsonccc** [comment]
PRs for this are all open at this point. Move anything relevant to those specific PRs.
