### ISSUE TITLE
People still don't know datavec exists

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#2511]
We already have a dedicated page for it, but maybe linking to examples for various formats could help?

**Comment by tomthetrainer** [comment]
I built two pages that help address this. 

This Page introduces the parts of DL4J
https://deeplearning4j.org/overview

This page walks through the datavec examples
https://deeplearning4j.org/examples-tour

I do have a goal of getting the good docs we have better indexed so that folks can find a place with everything that they need, with that in mind I will leave this open.
