### ISSUE TITLE
the score variable isn't be changed after initialized

### ISSUE THREAD

**Issue by liulhdarks** [deeplearning4j/deeplearning4j#2591]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/learning/impl/elements/SkipGram.java#L221

**Comment by raver119** [comment]
It's just a placeholder. 

Отправлено с iPhone

**Comment by raver119** [comment]
I mean: it was supposed to add scoring at some point, somewhere around 0.5.0 - 0.6.0 releases, but then we've got full overhaul of nlp stuff, and feature wasn't ever implemented. And right now i'm not sure if it'll be ever possible to implement it. Because execution is semi-asynchronous there, and it's usually impossible to say when exactly specific sg/cbow round will be accomplished.

And on new spark implementation that'll be even more crazy.
