### ISSUE TITLE
[Question] unwanted baterries included?

### ISSUE THREAD

**Issue by hrstoyanov** [deeplearning4j/deeplearning4j#2639]
I was going over the docs a couple of thigs got rub into my face right away:
- dl4j is tightly integrated with Spark and Hadoop. These are perhaps not my top choices for distributed data processing . Do I still have to put up with them for dl4j, even if I prefer other distributed frameworks such as Infinispan, Apache Ignite or Hazelcast?
- microservice archutecture. This is pretty contreversial approach, so I wonder how much of dl4j enforces it. Alternatively, can I just use dl4j as a library in say classic Java EE server configuration deployment?

Thanks.

**Comment by agibsonccc** [comment]
1. It has *spark integration* but doesn't rely on spark. We have it as a mode of training. We are explicitly mentioning hadoop and spark because that's what has market share. Skymind is a commercial company catering to enterprise. Most of those use hadoop/spark. Being an open source apache licensed project,y you are welcome to add alternatives. Dl4j can train on a single desktop or even run on an android phone. If you'd like to contribute and maintain an alternative to this we welcome pull requests. If you want to pay skymind to write one, you are welcome to open up a support contract for an engagement.

2. In 2017, I disagree. I know there's companies out there on J2EE. We have J2EE users, we don't *enforce* microservices. You can deploy a neural net however you want. A neural net in dl4j takes in ndarrays and outputs ndarrays. However you create and run those ndarrays is up to you. I know of many wildfly and tomcat based dl4j deployments.

**Comment by hrstoyanov** [comment]
thanks
