### ISSUE TITLE
NaN problem in LossCosineProximity.scoreArray(INDArray labels, INDArray preOutput, String activationFn, INDArray mask)

### ISSUE THREAD

**Issue by HuichuanLiu** [deeplearning4j/deeplearning4j#2654]
In the masked part, where input features and labels are usually zeros, the cosProximity becames 0/0=NaN, after that the mask was excuted NaN*mask=NaN, maybe the mask check could be brought ahead.

**Comment by HuichuanLiu** [comment]
@eraly May I have a schedule of this debugging? Quite important in our project. Thanks.

**Comment by agibsonccc** [comment]
@HuichuanLiu if you want priority support, please email help@skymind.io and we can arrange a support contract for you.We would be happy to put you in touch with our sales representatives. Otherwise, we can't guarantee when this will get done and don't give dates for these things.  It will get done when things get done.

**Comment by HuichuanLiu** [comment]
@agibsonccc OK, I see, will talk to my boss. Thanks.

**Comment by agibsonccc** [comment]
Thanks for being understanding! You get *a lot more* from us than just guarantees. Send over a list of requirements and we'll be more than glad to get you setup.

**Comment by eraly** [comment]
https://github.com/deeplearning4j/nd4j/pull/1582
You will have to build from source to get the fix.

**Comment by HuichuanLiu** [comment]
By _build from source_ do you mean decompile->modify codes->compile->replace the .class in the jar?

**Comment by AlexDBlack** [comment]
No, "build from source" means build the whole stack - libnd4j, nd4j, datavec, deeplearning4j, and use the resulting 0.7.3-SNAPSHOT instead of version 0.7.2 on maven central.

An alternative is to copy the new LossCosineProximity class to your project, and use it as if it was a custom loss function as per https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/lossfunctions. I'm not sure how that will work for to/from JSON though, given the existing (old) LossCosineProximity class still being available.

Also: I'm closing this as the issue should be fixed now.
