### ISSUE TITLE
build error on MacOSX: error: instruction requires: AVX-512 ISA

### ISSUE THREAD

**Issue by lefromage** [deeplearning4j/deeplearning4j#2668]
deeplearning4j-master/libnd4j/blas/cpu/NativeOps.cpp:2686:1: warning: option("tune=x86-64") is deprecated; use option("tune=k8") or option("tune=generic") instead as appropriate [-Wdeprecated]
/var/folders/2s/hfbmxgk13nv6rxdcfkx73w40b61sfl/T//cc3vF9Wo.s:651023:2: error: instruction requires: AVX-512 ISA

issue using script build-dl4j-stack.sh
https://gist.githubusercontent.com/crockpotveggies/9948a365c2d45adcf96642db336e7df1/raw/64329b463b014f466512d7c08028c3988660e23a/build-dl4j-stack.sh

**Comment by saudet** [comment]
Known issue with GCC 6.x, please use GCC 5.x for now.

**Comment by lefromage** [comment]
Thanks that worked!
exact SOLUTION: brew switch gcc 5.3.0

Cleaning /usr/local/Cellar/gcc/5.3.0
Cleaning /usr/local/Cellar/gcc/6.2.0
Cleaning /usr/local/Cellar/gcc/6.3.0_1
30 links created for /usr/local/Cellar/gcc/5.3.0

my versions were: 
brew list --versions gcc
gcc 5.3.0 6.2.0 6.3.0_1

**Comment by noloader** [comment]
Sorry for digging up an old bug report. I came across this issue report when searching for our instance of the problem.

Also see LLVM Issue 39875, [Error: instruction requires: AVX-512 ISA when using -mavx512f](https://bugs.llvm.org/show_bug.cgi?id=39875). The short of it is, Clang 7.0 is needed to sidestep a problem with the Clang integrated assembler. The root cause is LLVM Issue 36202, [llvm-mc doesn't accept AVX512 instructions using %zmm16+](https://bugs.llvm.org/show_bug.cgi?id=36202).

**Comment by raver119** [comment]
@noloader thanks
