### ISSUE TITLE
Null TestSetRegressionScore using arbiter

### ISSUE THREAD

**Issue by edb2016** [deeplearning4j/deeplearning4j#2728]
###Error###
INFO  [2017-01-23 21:26:24,538] org.deeplearning4j.arbiter.optimize.runner.BaseOptimizationRunner: Completed task 0, score = null
###

###GIST showing where the problem occurs###
https://gist.github.com/edb2016/79b60a9dbc61e869b712e63920c85644 

But basically the candidate.getDataParameters() returns null and hence the score is null.

###GIST of my local network config for arbiter & candidate generator###
https://gist.github.com/edb2016/ffa50060fad6a505600d197774e7ad0a

**Comment by edb2016** [comment]
If you have any questions regarding the issue email me at e_db@hotmail.co.uk. I was advised to raise this as a bug after speaking to Melanie Warrick

**Comment by edb2016** [comment]
Please let me know if there is any potential work around, thanks

**Comment by edb2016** [comment]
Here is a GIST of the dataset iterators that I used to point to CSV files along with the data provider.
https://gist.github.com/anonymous/0400a83bde261a0a856791448081a7f4

**Comment by edb2016** [comment]
Hi I have been doing some investigation and it looks as though its null because an exception is thrown in the next.getLabels().columns() method passed in the constructor . Its expecting 2d but my data is 3d. Please see code snippet.

https://gist.github.com/edb2016/9fac52b07fa9e8dc3eeb380652d73711

**Comment by edb2016** [comment]
As above I've done some research myself as to why my next.getLabels() is returning a 3d array and not 2d.

1) I'm using CSVSequenceRecordReader & SequenceRecordReaderDataSetIterator to read my CSV files. I can see the BaseNDArray init method being called and setting the rank to 2. However if I look at my DatasetIterator, call next().getLables() it returns and NDArray with rank 3. I have no idea how or why this is happening

2) I can also confirm the SequenceRecordReaderDataSetIterator->nextMultipleSequenceReaders method is creating a INDArray for labels with dimensions of 2d

So given the above two points I don't understand how it can return a rank of 3??

**Comment by AlexDBlack** [comment]
@edb2016 I think I've isolated the problem: the fix is relatively simple (and you should be able to utilize it without having to build from source)

Can you copy the following code into your own project, and use it in place of the existing (built-in) TestSetRegressionScoreFunction?
https://github.com/deeplearning4j/Arbiter/blob/b6a1c5864aba88c5e8476006be947f8fa94c5a2b/arbiter-deeplearning4j/src/main/java/org/deeplearning4j/arbiter/scoring/multilayer/TestSetRegressionScoreFunction.java

That is taken from the following pull request: https://github.com/deeplearning4j/Arbiter/pull/56

**Comment by edb2016** [comment]
Issue fixed!

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/Arbiter/pull/56
