### ISSUE TITLE
Currently failing unit tests

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2745]
TestUpdater.testMultiLayerUpdater (due to Adagrad shape issue, possibly due to the test itself, not anything in Adagrad)

RBMTests.testActivate

DataSetIteratorTest.testBatchSizeOfOne (cifar iterator)

ModelGuesserTest.testModelGuess

Edit: also noticing some issues with incorrect warnings on updater configuration (epsilons, etc). Possibly due to this: https://github.com/deeplearning4j/deeplearning4j/pull/2706/files

**Comment by agibsonccc** [comment]
Post PR merge for keras/model guesser:
https://gist.github.com/agibsonccc/f77379ee05ede01bf338c7ac82e765cf

This is on keras/simple/lstm_tf_model.h5" using the ModelGuesser.

**Comment by turambar** [comment]
@agibsonccc @eraly import on that LSTM model fails due to an unsupported weight initializer in the LSTM ([orthogonal](https://github.com/fchollet/keras/blob/master/keras/initializations.py#L88)). For what it's worth, we also do not support Keras' "identity" weight initializer.

Running with `enforceTrainingConfig=false` for now will bypass the error, but another error crops up related to importing time distributed dense layers.

**Comment by turambar** [comment]
Relevant issues that are breaking the model import unit tests:
* https://github.com/deeplearning4j/deeplearning4j/issues/2747 <-- should be simple fix
* https://github.com/deeplearning4j/deeplearning4j/issues/2748 <-- an be bypassed

**Comment by huitseeker** [comment]
AFAICT this is superseded by #2784 and should be closed as duplicate (thanks for the fixes @turambar )

**Comment by AlexDBlack** [comment]
Yes, superseded by this: https://github.com/deeplearning4j/deeplearning4j/issues/2784
The issues mentioned in this issue have also been fixed (at least according to my testing on this branch: https://github.com/deeplearning4j/deeplearning4j/pull/2872)
