### ISSUE TITLE
Recurrent Network Resets Context Each Time

### ISSUE THREAD

**Issue by JosephCatrambone** [deeplearning4j/deeplearning4j#292]
Opening a ticket as requested.

Right now, each time activate() is called, the hIn of the network is cleared.  Let's say we have a trained neural network on this kind of input data.

"The child sat on the chair."

"The cat sat on the bed."

Note that the word after "the" depends on the word from two tokens earlier.  As it stands, if we are training a network, it looks like line 180 (https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/recurrent/LSTM.java#L180) is clearing the context each activation.  If we are emulating a conversation and we'd like to reply to, "It sits on the?", it would be helpful to be able to set the state of hIn so that we can set the context of the network.

EDIT: Hopefully more coherent now.

**Comment by Subby4Git** [comment]
Is there any update on this? This would be excellent for contextual spoken language understanding!

For example, the following conversation:
- What is the weather in Berlin?
- Any restaurants there?

In the second question, the network would need to maintain the context.

Also, for maintaining the context, it would be nice if an id parameter can be passed into the network, so that it maintains the context for each id (each user)...

**Comment by nyghtowl** [comment]
RNNs have been completely reworked from last year and this no longer is an issue.
