### ISSUE TITLE
UI not working for RRNs

### ISSUE THREAD

**Issue by Stevod** [deeplearning4j/deeplearning4j#2925]
I have two different LSTM projects, based on the SeqClassificatiion example, and neither works with the UI at localhost:9000.
Screen shot attached, along with a console log file from Chrome on Ubuntu. It does not work with Edge on Win 10 either, though the console messages are different for each browser type.
![dl4j-ui](https://cloud.githubusercontent.com/assets/6758915/23339259/59eb407a-fc16-11e6-9837-115e27f04b51.jpg)
These are all the errors in the Chrome console:
[DJ4J-UI-Errors_chrome on ubuntu.txt](https://github.com/deeplearning4j/deeplearning4j/files/801901/DJ4J-UI-Errors_chrome.on.ubuntu.txt)

**Comment by AlexDBlack** [comment]
@Stevod can you post the configuration you are using, and how you are generating the data?
We'll need to reproduce this before we can start debugging it.

**Comment by Stevod** [comment]
Hi Alex, I work in a sensitive field, hence don't want to post the code where it's publicly available. Is there anyway I can send you it so it isn't public?

**Comment by raver119** [comment]
Send in gitter directly to Alex?

**Comment by Stevod** [comment]
How - I don't have his email address?

**Comment by raver119** [comment]
Check your pm in gitter.

**Comment by Stevod** [comment]
Code sent in email direct to AlexDBlack

**Comment by AlexDBlack** [comment]
@Stevod I ran your data: there's 2 things here
- First: the javascript errors are due to no data being available in the UI - that's fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2953
- Second: your data pipeline is resulting in time series of around 24k length, so each sequence is taking forever to actually do anything (which is why you don't have data in the UI - it's still processing, having not finished one iteration probably). As an aside, the architecture you are using isn't ideal for the type of classification you are trying to do - direct message me on gitter if you want some suggestions there.
