### ISSUE TITLE
compilation error SparkDl4jNetworkTest.java

### ISSUE THREAD

**Issue by kepricon** [deeplearning4j/deeplearning4j#3147]
[SparkDl4jNetworkTest.java](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark-ml/src/test/java/org/deeplearning4j/spark/ml/impl/SparkDl4jNetworkTest.java) has a compilation error like below.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project dl4j-spark-ml_2.11: Compilation failure
[ERROR] /home/nvadmin/skymind/git/dl4j-build/deeplearning4j/deeplearning4j-scaleout/spark/dl4j-spark-ml/src/test/java/org/deeplearning4j/spark/ml/impl/SparkDl4jNetworkTest.java:[11,28] cannot find symbol
[ERROR] symbol:   class DataFrame
[ERROR] location: package org.apache.spark.sql
[here](https://gist.github.com/kepricon/996f6a809f2eb5ac170fcefdbe441cb9) is more info.

@dmmiller612 could you please fix it? @agibsonccc

**Comment by dmmiller612** [comment]
I am guessing your default spark version is for 2.0? This test is more focused around 1.6.

**Comment by dmmiller612** [comment]
With that in mind, I sort of thought 1.6 was used by default for tests. Since Dataframe is doesn't exist as a usable class in 2.0, it is tricky because 1.6 uses it exclusively. Also, in 2.0, spark wants you to use Vectors from ml, instead of mllib. It would have to follow a similar pattern with the sub-packages, I think, to get it working.
