### ISSUE TITLE
Data Structure for Spark deeplearning4j

### ISSUE THREAD

**Issue by bradou10** [deeplearning4j/deeplearning4j#3166]
Hi guys, 

Please, I have been looking for all over the web since days to figure out an issue, so any help will be grateful !!

So, I am actually trying to run a deep neural network (MLP - Regression) using deeplearning4j in Spark (SCALA) for times series (not RNN). I have found out few examples of classifications in java, scala, ... But I struggled a lot to get what I want with Spark Scala (I am new in spark scala) in regression. 
I think I have understood the different points of create a neural network using Spark but I still don't understand how to get the good structure of the data. 

First of all, I have a json data that I import using spark.sql in a dataframe [x, y, z, w, ... ] then I know I need  to get a RDD[DataSet] structure to train the MLP in a spark network SparkDl4jMultiLayer, but I don't know how to cast the dataframe to an RDD[DataSet] (I have also a CSV file instead of the json file)
The simple example that I am trying to run is a simple dataset with 3 features (temperatures, consumption1, consumption2) and I'd like to run a deep MLP regression predicting "consumption2" from temperatures and consumption1. It's not mathematically what I would like to do later (times series prediction based on a time structure) but I'd like to get this work (for a beginning) then I could make a more complicated approach. 

If someone can help me giving me something step by step to follow (deeplearning4j for Spark in scala), I will be very grateful ! 

Thanks a lot !!

**Comment by tomthetrainer** [comment]
Take a look at our Spark Examples

Here might be the code you are looking for. 

  DataSetIterator iterTrain = new MnistDataSetIterator(batchSizePerWorker, true, 12345);
        DataSetIterator iterTest = new MnistDataSetIterator(batchSizePerWorker, true, 12345);
        List<DataSet> trainDataList = new ArrayList<>();
        List<DataSet> testDataList = new ArrayList<>();
        while (iterTrain.hasNext()) {
            trainDataList.add(iterTrain.next());
        }
        while (iterTest.hasNext()) {
            testDataList.add(iterTest.next());
        }

        JavaRDD<DataSet> trainData = sc.parallelize(trainDataList);
        JavaRDD<DataSet> testData = sc.parallelize(testDataList);


Taken from https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/mlp/MnistMLPExample.java

If you download our examples repo, there are multiple Spark examples.

**Comment by bradou10** [comment]
HI Tom, 

Thanks a lot for your answer. However, I have already taken a look to this example, but there is something I stuggled to figure out, because of the way this example use a Mnist example (image file), and I don't understand the structure of the file, it's like most of the functions in this example are used for "Mnist", but if you wanna change the file, like used this kind of file : https://archive.ics.uci.edu/ml/machine-learning-databases/00235/  so it's more complicated to used this loaded file example ?!
Hope you get what I'm mean ! 

ps: I downloaded the repo but I can't find any examples similar to my loading problem (just load a dataset with deeplearning4j in scala for SPARK)

Thank you

**Comment by agibsonccc** [comment]
I'm not sure what you mean "just load a dataset". A dataset by definition is open ended. This is what datavec is for. The only thing we need is RDD<DataSet>, you can obtain that several ways. As Tom mentioned we have *several* spark examples:
https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j

If you want to solve a basic problem, you can do pre processing like this:
https://github.com/deeplearning4j/dl4j-examples/blob/master/datavec-examples/src/main/java/org/datavec/transform/basic/BasicDataVecExample.java

Once you have a List<Writable> Rdd, you can run a simple map function:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/datavec/DataVecDataSetFunction.java

which gives you a dataset.  I'm closing this - if you have a more specific question rather than "Solve my problem for me!!!11!!"  then ask in gitter. You can't and shouldn't expect our examples to cover every conceivable use case. If we are missing a use case *add it*.

**Comment by bradou10** [comment]
OK, I finally get what you mean, I think datavec is the good way to figure out what I would like to do !

Thanks a lot !!!

**Comment by bhorkar** [comment]
@bradou10 , 
have you been able to resolve the issue?. I am exactly looking at the same problem.  The functionalities provided by spark Dataset are much better. Hence, datavec approch may not always be best.

**Comment by agibsonccc** [comment]
@bhorkar please open a separate issue  with what datavec is missing. The reason we use datavec here is because it works for both non spark and spark use cases and it allows us to control the conversion of input data for off heap memory.

The "functionalities" in the spark dataset end up being a big performance issue when you actually get down to it. I'm not sure what you exactly think "good" is, but in general - there's a reason we have our own stack for doing this.

**Comment by bhorkar** [comment]
I understand datavec should should be the way to go. I think, datavec misses window functionality of spark dataset for my use case. 
In my use case, we are using dl4j's LSTM.  I have a large csv files, from which we need to construct a time-series dataset.   
We use spark dataset  to create the time-series. 
        WindowSpec win = Window.partitionBy("key").orderBy("timestamp").rowsBetween(-(exampleLength - 1),0);
        dataDf = dataDf.withColumn(column_output,functions.collect_list(cell_dataDf.col(column_input)).over(win));
Here dataDf is the spark dataset. 
Once, we have the time-series as spark dataset, we then convert to JAVARDD. Finally, i am planning to convert javardd to dl4j dataset of type javardd<dataset>.  I did not find similar functionalities of time-series in datavec. I am looking at examples such as https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/rnn/SparkLSTMCharacterExample.java
