### ISSUE TITLE
DataSet.shuffle() experiencing Fatal Error

### ISSUE THREAD

**Issue by szingerpeter** [deeplearning4j/deeplearning4j#3714]
When using the **shuffle** method on a **DataSet** object I sometimes get the following error log:
[error](https://gist.github.com/szingerpeter/ea4d48eeb9861982554db119b312d241)

I was able to reproduce the issue with the following code:
[code](https://gist.github.com/szingerpeter/bdf07a445d12b7b27ba7b354ddb1a91f)

However, I need to run the previous code up to 5 - 10 times consecutively to get to the error.
DL4J: 0.8.0
OS: Ubuntu

Thank you for any help!

**Comment by agibsonccc** [comment]
@raver119 didn't you fix this already?

**Comment by raver119** [comment]
No, not yet, still testing long tads. Will fix it till the end of day

**Comment by raver119** [comment]
Well, this code is invalid by definition, and shouldn't work.

After DataSets.merge()  you get 2 INDArrays within DataSet with following shapes:
```
Shape [2, 75, 25, 25, 1, 0, 1, 99];
Shape [2, 3, 1, 1, 1, 0, 1, 99];
```
It clearly can't work and shouldn't work, because shuffle for datasets works for dimension 0, and two arrays have different numbers of rows. 

So this is input validation issue. This code shouldn't work.
