### ISSUE TITLE
Add SRU RNN Implementation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4085]
https://arxiv.org/abs/1709.02755

SRU = "Simple Recurrent Unit". Much faster to train and equal/better performance (according to authors) vs. LSTM etc.

It may make sense to implement this directly as a native layer, rather than first building a Java-based version?

**Comment by tomthetrainer** [comment]
@AlexDBlack 
only tangentially related to the ticket, but if you could at some time summarize for me the term "native layer" 

Thanks

**Comment by agibsonccc** [comment]
Pure c+++. No java.

**Comment by tomthetrainer** [comment]
Yeah I figured that much, will ask more in another forum :-)

**Comment by agibsonccc** [comment]
Not sure what more color to add beyond that we have a lot of layer logic
moving to libnd4j.

**Comment by raver119** [comment]
Ye, all new layers coming since last week are coming compatible with dl4j AND with SameDiff (soon) - these layers are Ops. 2 or 3 ops per layer.
1) ff pass op
2) epsilon calculation op (same op name, _bp suffix)
3) gradients calculation op (if applicable!, _grad suffix). 

So, on java side we'll have layer that'll has 3 op calls internally + some configuration validation. I.e. recently added UpsamplingLayer uses this mechanic. And all magic will be happening in C++ and as already mentioned, will be compatible with both DL4j and SameDiff

**Comment by raver119** [comment]
SRU is implemented at libnd4j level. Waiting for java integration.
