### ISSUE TITLE
deeplearning4j - nlp - tokenizerFactory / tokenizerfactory - compilation error

### ISSUE THREAD

**Issue by clavvis** [deeplearning4j/deeplearning4j#4190]
I tried to import deeplearning4j 0.9.2 SNAPSHOT in Eclipse as a Java project. I received this error:

The project was not built due to "A resource exists with a different case: '/deeplearning4j/bin/org/deeplearning4j/text/tokenization/tokenizerFactory'.". ....

I found in chinese nlp "tokenizerFactory!, but other has " tokenizerfactory"

I use Windows (10).

**Comment by agibsonccc** [comment]
You don't need to do do snapshots. Just use normal maven please.

**Comment by clavvis** [comment]
To solve this problem is probably necessary only rename one folder. Whay is this problem?

**Comment by raver119** [comment]
You mean we have capitalized folder/package name somewhere?

ср, 18 окт. 2017 г. в 17:03, clavvis <notifications@github.com>:

**Comment by agibsonccc** [comment]
Hmm..I'm not sure what could have changed if any, it's right here:
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/activationfunctions/CustomActivationExample.java

The package name declarations are right. I'm suspcious because we haven't touched the chinese module.

**Comment by raver119** [comment]
https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j-nlp-parent/deeplearning4j-nlp-chinese/src/main/java/org/deeplearning4j/text/tokenization

Yes, minor bug was unnoticed earlier. Easy fix.

**Comment by raver119** [comment]
Issue fixed long ago.
