### ISSUE TITLE
pom.xml in docker files breaks build-dl4j-stack.sh

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#4262]
#### Issue Description

If you try to use the build stack script, it will fail on the following:

```
[ERROR] [ERROR] Could not find the selected project in the reactor: dl4j-examples/tutorials/docker @ 
[ERROR] Could not find the selected project in the reactor: dl4j-examples/tutorials/docker -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* master

#### Contributing

Will either change filename or

**Comment by crockpotveggies** [comment]
https://gist.github.com/crockpotveggies/b3941f40b0fa324767d862d8933b90bf

**Comment by huitseeker** [comment]
This is due to the version-changing scripts ( changescalaversions, change spark version), which detect the pom files which have been affected by the versions change in the repo, and from that try to compute which modules should be recompiled.

Sadly, this pom file does not correspond to any module that should be part of the compilation of dl4j.

The fix is to make sure it's not named pom.xml, which is done in https://github.com/deeplearning4j/deeplearning4j/pull/4268#event-1332770775
