### ISSUE TITLE
Layers do not clear inputs, even when they are invalidated by workspaces

### ISSUE THREAD

**Issue by schrum2** [deeplearning4j/deeplearning4j#4291]
#### Issue Description

This short code gist runs VGG16 with image net weights and then tries to analyze the intermediate activation of a particular layer:
https://gist.github.com/schrum2/254dec555ba6908c8f8a21f3141e023c

I have successfully used VGG16 before, but only the final outputs. However, when I run this code, it crashes with a Fatal Error:

https://gist.github.com/schrum2/1cc1fb41971c9a4d0a284f366ecc7706

The full error contents of the error report file are here:

https://gist.github.com/schrum2/5e47cf3d7023b8d06b5291f6d0e38943

It's possible I'm using the activate() method wrong, but even if I am, it seems in appropriate to receive a fatal error rather than a more straight forward exception.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.1
* platform information (OS, etc): Windows 10

**Comment by AlexDBlack** [comment]
This appears to be due to workspaces, and (given the use of workspaces by default for inference).
In short, it's trying to do forward pass with memory that has already been deallocated.
If you aren't familiar with workspaces, read this: https://deeplearning4j.org/workspaces

Moving forward, no-arg methods like activate() will be for internal use only - in part because this sort of "stateful" behaviour will be changed.

Anyway, to get the activations you want: you can use the feedForward methods on ComputationGraph, with return a ```Map<String, INDArray>``` of activations.

**Comment by schrum2** [comment]
The feedForward method seems to work fine. Thanks for the quick response.

From my perspective, the issue is resolved, but I don't know if you want to leave it open until the activate method is made private.

**Comment by AlexDBlack** [comment]
Yeah, I'll leave the issue open as a reminder to fix this - regardless of what we do here, we don't want users running into this in the future.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4326
