### ISSUE TITLE
Training UI sometimes leaves out important peaks.

### ISSUE THREAD

**Issue by SanderGielisse** [deeplearning4j/deeplearning4j#4385]
#### Issue Description
Big peaks which could be really important seem to be left out randomly. Seems to apply to the latest UI version.

How the plot is often shown:
![](http://sandergielisse.nl/deeplearning4j/ea64289fee8a05647741998c3c71a0fe.png)

How the plot is shown at random points in time:
![](http://sandergielisse.nl/deeplearning4j/067db4c2b4da410878e961d00c57abeb.png)

I checked the peaks are actually there, but they were simply not shown.

**Comment by AlexDBlack** [comment]
This is due to subsampling of the points - once we get enough data, we start showing every 2, every 4, every 8 etc points.
You can increase the number of points using this sytem property:
https://github.com/deeplearning4j/deeplearning4j/blob/63f48c6eb76329955150361c1a48497790ecc9c9/deeplearning4j-ui-parent/deeplearning4j-play/src/main/java/org/deeplearning4j/ui/module/train/TrainModule.java#L57-L58

Beyond that, I'm not sure this is something we what to change the defaults for (and, I'm not sure what the fix would be other than always showing all points, which will be impractical for long training sessions).
