### ISSUE TITLE
Implement "The Transformer"

### ISSUE THREAD

**Issue by mdavis95** [deeplearning4j/deeplearning4j#4454]
#### Issue Description

Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by agibsonccc** [comment]
Sorry we don't take feature requests like this. Whatever "custom random thing" you want us to implement will the form of tensorflow/keras import + samediff next release which will handle allowing you to copy and paste whatever you want.

**Comment by mdavis95** [comment]
Fair enough but not exactly what I was doing.  I have had good luck using recurrent neural networks to do citation parsing in d4j.  My colleague suggested this might help improve my results further and reduce training time.

**Comment by agibsonccc** [comment]
Right that's fine. In general it's just not worth it for us to support research. The architectures are too archaic, it's usually for minimal gains, and just isn't worth our time. We're a business. Most people who actually deploy deep learning applications don't search for these kinds of architectures.  That's why we're just introducing our own autodiff framework and model import. That way people can just do what they want and you just plug it in to dl4j instead.
