### ISSUE TITLE
Doc for importing Keras model in android ?

### ISSUE THREAD

**Issue by pkarira** [deeplearning4j/deeplearning4j#4482]
is there any official docs for code given in video on following page https://deeplearning4j.org/model-import-keras#keras? And how to make prediction after importing ?

**Comment by saudet** [comment]
HDF5 isn't supported on Android, so import on the desktop, save, and load on Android.

**Comment by pkarira** [comment]
and how to make predictions by using imported keras model ? is there any doc for code given in video?

**Comment by saudet** [comment]
It's all here: https://deeplearning4j.org/build_vgg_webapp

Not sure if there's a video detailing everything, @tomthetrainer ?

**Comment by tomthetrainer** [comment]
No there is no video detailing everything. 

We could use a more prominent doc on inference. 

@pkarira 

The basic path for prediction is 

1. Load the Trained Model
2. Use model.output(YourInputArray) to get your output Array

If you are importing a Keras Model then Model is created using KerasModelImport(Path to your h5 file) 

Since you are on Android and h5 is not supported then a path for you would be to 

Load Model on Linux/Mac/Windows using KerasModelImport. 
Save Model on Linux/Mac/Windows using ModelSerializer

ModelSerializer saves as a Zip file. 

Load Model on Android using ModelSerializer 

Use model.output(yourInput) to make predictions. 

The VGG web app described above uses Sparkjava (I think that is what it is called) to make a web (REST) interface for predictions.  Perhaps a more proper way would be to bundle things up as a servlet in Tomcat. Servlet development is a little more complex than plain old java, so if you are new to java it might be a bit challenging. 

Here is a repo with some "servlet in tomcat" examples. 

https://github.com/SkymindIO/RestDemos

This should come close to what you are after, those examples have models saved with modelSerializer and loaded using modelSerializer and then a web app waiting to do predictions. 

That code should get you started.

**Comment by nkwoh01** [comment]
@tomthetrainer @saudet @pkarira This looks resolved.

**Comment by saudet** [comment]
@nkwoh01 Not resolved yet, but this is something Jason Merwin (would you know his GitHub username?) should be working on.

**Comment by agibsonccc** [comment]
@jrmerwin

**Comment by merwijas** [comment]
Yes you will need to train the model on desktop and then include the zip file in the res folder of the app. I'm working on loading and using models in Android now. I'll give a link to the documentation for it when finished.

**Comment by jrmerwin** [comment]
@pkarira This approach loads and uses a pre-trained model in Android:
 
1.	Train yourModel on desktop and save via modelSerializer (as described above).
2.	Create a raw resource folder in the res directory of the app, if it does not already exist.
3.	Copy yourModel.zip file into the raw folder.
4.	Access it from resources using an inputStream like so:
 ```java
try {
// Load yourModel.zip file using inputStream.
        InputStream is = getResources().openRawResource(R.raw.yourModel);
 
// Restore yourModel.
        MultiLayerNetwork restored = ModelSerializer.restoreMultiLayerNetwork(is);

// Use yourModel.
        INDArray results = restored.output(input)
        System.out.println("Results: "+ results );

// Handle the exception error
} catch(IOException e) {
        e.printStackTrace();
    }
```
also, be sure to include the dependency below or using the loaded model will cause a buffer error.

'org.bytedeco.javacpp-presets:systems-platform:1.4'

**Comment by pkarira** [comment]
Thanks a lot @jrmerwin
