### ISSUE TITLE
model-import depends on hdf5-platform

### ISSUE THREAD

**Issue by johanvos** [deeplearning4j/deeplearning4j#4566]
There are a number of pom files (e.g. deeplearning-modelimport/pom.xml) that depend on hdf5-platform. As a result, a large number of jars containing native code will end on the classpath, and in the case of mobile apps this native code will be contained in the apps. The native libraries will be ignored if they don't match the native platform, but they make the apps much bigger.

**Comment by AlexDBlack** [comment]
A workaround here may be to exclude them and add only the required native libraries.
The alternative (have users add for each platform) is too error prone for users. Downloading dynamically at runtime probably isn't viable either due to the requirement for network access.

Only other idea I have here would be to write say a JavaCPP Maven plugin that allows you to specify the deployment target(s), automatically excluding the native binaries from all other platforms, for JavaCPP presets... @saudet that wouldn't be trivial to implement, but is it worth considering here?

**Comment by saudet** [comment]
That's already possible with Maven, we just need to set the "javacpp.platform" system property.

@johanvos I'm guessing that you are talking about Gradle though? Unfortunately, Gradle doesn't work with Maven profiles, but it would be possible to create a Gradle plugin that does the equivalent too. So, question, why do you need Gradle? What is missing from Maven?

**Comment by AlexDBlack** [comment]
@johanvos https://github.com/deeplearning4j/dl4j-examples#build-and-run
More details on the system property with maven (I wasn't aware of that until now). No support yet for multiple (but not *all*) platforms, beyond configuring things manually.

**Comment by saudet** [comment]
To answer my own question, I guess the idea is to cater to Android developers, so it needs to work well with Gradle...

I'll create a repository on http://bytedeco.org ("gradle-javacpp" I guess) and let me know if you have anyone to assign for this. Just about anyone should be able to do that, right?

**Comment by nkwoh01** [comment]
@AlexDBlack @saudet @johanvos This looks resolved so I'm closing it.

**Comment by saudet** [comment]
@nkwoh01 Well, it's not resolved, but it's not about deeplearning4j either.
