### ISSUE TITLE
multi dimensional lstm in dl4j?

### ISSUE THREAD

**Issue by doofin** [deeplearning4j/deeplearning4j#4742]
Are there multi dimensional lstm implemented in dl4j for images ? If not , How to  implement them? Should it be implemented using computational graph for dl4j or have to go  lower level to nd4j?

**Comment by saudet** [comment]
There is an RnnToCnnPreProcessor for that. It doesn't do much, but it usually get the job done. There is an example using it here: https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/video/VideoClassificationExample.java

**Comment by AlexDBlack** [comment]
@saudet no, multi-dimensional RNNs are a different architecture. Different to - and much more complex than the video examples.
https://arxiv.org/pdf/0705.2011.pdf

Do we have them? No - and unfortunately we're unlikely to support them any time soon. They aren't supported in Keras for example either.

As to how you would code them: definitely not at the DL4J computation graph level. Either at the layer level, *or* (once it's completely ready) using the new SameDiff API. Either way, you're still talking a *lot* of work to get it going. I'd wager more time/effort than you'd be prepared to commit.

If you are looking for image segmentation, I'd consider a CNN-based architecture for that.

**Comment by doofin** [comment]
Wow, so It seems that going as low level as nd4j is unavoidable,then which part of dl4j can be reused ? If I have to only write the forward network and reuse  back-propagation-through-time for lstm then it'd be ok

**Comment by doofin** [comment]
@AlexDBlack  why is this issue closed so abruptly given that  you don't even know how to do it ? A key component of mdLstm  has already been implemented in tensorflow offically (https://www.tensorflow.org/api_guides/python/nn#Connectionist_Temporal_Classification_CTC_) . Your action is pushing users out of dl4j

**Comment by AlexDBlack** [comment]
I closed it abruptly because I understand the complexity of what you are asking. I have implemented the majority of DL4J's RNN functionality, so I'm well placed to estimate the complexity of such a layer.

And again, even Keras does not support it.

Note that CTC and multi-dimensional RNNs are very different architectures - they are independent layers.

> Your action is pushing users out of dl4j

I'm sorry that you feel that way, but I have to disagree. We have to focus on high priority features, and MD-RNNs don't come up much. Sure, I'd love to have MD-RNNs, but it's not a priority at this time - the ROI isn't there for us to focus on it at this point. If you genuinely want to put in the time to implement such a feature, then I'd be happy to point you in the right direction.

**Comment by doofin** [comment]
No worry. The CTC is something independent,my mistake.However,I would like to try implement CTC and if try 1d lstm first for handwriting recognition,and depends on the result I might try 2d one . This is for my bachelor graduation  thesis so I got plenty of time and incentive to do so,thank you for providing some directions!
