### ISSUE TITLE
KMeansClustering cause thread leak

### ISSUE THREAD

**Issue by gogo111007** [deeplearning4j/deeplearning4j#4766]
#### Issue Description

i use KMeansClustering like KMeansTest.java
every client request, i get new kmeans object by KMeansClustering.setup()
but there is no way to destroy threads allocate by KMeansClustering 
after thousands or more request, too many threads cause crash

#### Version Information

* deeplearning4j ver newest
* windows 7 and centos 6.x

**Comment by jentfoo** [comment]
I recently stumbled across this too.  The issue is in `BaseClusteringAlgorithm`.  It constructs an `ExecutorService` but provides no way to free it.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nearestneighbors-parent/nearestneighbor-core/src/main/java/org/deeplearning4j/clustering/algorithm/BaseClusteringAlgorithm.java#L70

I would be happy to help provide a PR to solve this if the maintainers give me some direction as to how this should be resolved.

the jdk attempts to implement a finalizer in `ThreadPoolExecutor` to shutdown the pool if it is garbage collected, however this does not work correctly if threads are started since they also hold a reference to their parent pool (and thus the finalizer is never invoked even if BaseClusteringAlgorithm is garbage collected).

If you wanted to rely on garbage collection I see two possible options:
1) Selfish plug of using a better thread pool.  Thread pools from my `threadly` project do not suffer from this issue.  They can be collected normally, or you can use `CentralThreadlyPool` as a way to avoid needing to manage the lifecycle at all.
2) You can implement a finalizer in `BaseClusteringAlgorithm` which invokes a shutdown to it's retained pool.

I personally don't like depending on finalizers.  My personal preference (though potentially unpopular) would be to have people supply an `Executor` (`Executor` is way better than `ExecutorService` if you can), and then put the thread pool management on the user.

If you are willing to depend on threadly, if an executor is not provided using a threadly executor can provide the ability to fall back to garbage collection for releasing the created threads.

**Comment by jentfoo** [comment]
I guess after looking at `ExecutorServiceProvider` maybe the original intention was to set `instance` (which currently goes unused) and reuse that instance.

**Comment by saudet** [comment]
@jentfoo Thanks for the input! Using threadly looks like a good technical solution, but I think the Mozilla license is a problem, @agibsonccc ?

**Comment by agibsonccc** [comment]
We follow apache legal guidelines: https://www.apache.org/legal/resolved.html It doesn't appear to conflict with the EPL, I'd be ok with this in that case.

**Comment by saudet** [comment]
Yes sounds good, go ahead with the PR, thanks!
