### ISSUE TITLE
ComputationGraph - wrong masking

### ISSUE THREAD

**Issue by Loewave** [deeplearning4j/deeplearning4j#4822]
#### Issue Description

If creating a network with ComputationGraph LSTM->Max Pooling -> Merge 2 LSTM's -> Output the masking is done wrong. Expected output is classification.
Error message:
`Invalid mask array: per-example masking should be a column vector, per output masking arrays should be the same shape as the output/labels arrays. Mask shape: [1, numberOfLinesInSequence], output shape: [1, 2]`

#### Version Information

* Deeplearning4j version: 0.9.1
* platform information: Linux

Code:
network:
https://gist.github.com/Loewave/51627b7b0777ea8df38b7b555c32b810
data pipeline:
https://gist.github.com/Loewave/16937c41d1ee7d44d96ae28d5a9bba17

**Comment by AlexDBlack** [comment]
OK, so I see the problem here: the data pipeline and network configuration are fine in isolation, but are mismatched
your data pipeline produces sequence data for both the features and labels... but your network is configured for sequence inputs (i.e., RNN layers) and non-sequence labels (i.e., OutputLayer)


Assuming your %d_labels.csv files have just one line each (i.e., a single label), your best option is to switch to something like the following:
https://gist.github.com/AlexDBlack/0068456810f78124eec18340b74f6a98

I'm not totally following what the goal there with the "AndereWerteLabel" part of your data pipeline though. Could just be a mistake? anyway, using the same reader there multiple times almost certainly won't work.

If that's not the case, and you have multiple labels per sequence, then the problem is your choice of network architecture (remove the pooling, replace OutputLayer with RnnOutputLayer).
