### ISSUE TITLE
Windows CUDA compilation time

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#5229]
It's time to migrate from nmake and start using anything that will allow us parallel compilation on Windows. JOM, Ninja, whatever. 15 minutes for 1 cc is too much.

**Comment by raver119** [comment]
cc @sshepel @saudet

**Comment by saudet** [comment]
The standard option on Windows for CUDA is MSBuild. It works well enough for OpenCV and TensorFlow, and supports parallel compilation, but not for CUDA apparently... CMake seems to support Ninja for CUDA since version 3.8: https://cmake.org/cmake/help/v3.10/release/3.8.html I wonder if that does any better.

**Comment by raver119** [comment]
CMake supports ninja and jom, and both do support parallel builds. So, anything that works for us here - would be just awesome to get integrated.

**Comment by saudet** [comment]
Ah, JOM is still NMake: https://cmake.org/cmake/help/v3.10/manual/cmake-generators.7.html#makefile-generators  That should work too, but again no guarantees that it builds in parallel for CUDA.

**Comment by raver119** [comment]
Implemented

**Comment by raver119** [comment]
6 mimutes for 1 cc now, 26 minutes for all ccs
