### ISSUE TITLE
New layer API causes regression in old API (nIn, nOut erroneously set to zero)

### ISSUE THREAD

**Issue by jyt109** [deeplearning4j/deeplearning4j#535]
- Rename `overRideField` to `overrideField` 
- Check integration of new API with the old

Certain neuralnetconfig properties seem to regress back to their default values. The problem is related to the new layer conf stuff. The overRideFields method sets the netconf’s property values to equal that of the layerconf’s values. But that makes sense only if you’re using the new API, otherwise the layerconf’s values are meaningless.

**Comment by EronWright** [comment]
A clear solution is to remove from NeuralNetConfiguration any properties that are now defined at the layer level.   e.g. nIn, nOut, activation, weightInit, dist, dropOut.    The present solution is broken and is causing unintended behavior.

**Comment by EronWright** [comment]
I spent a little time looking at the handling of default values here.  Two issues I see:

1. Enums - no default value handling of enums leads to many instances of HiddenUnit/VisibleUnit regressing.
2. NaN - be aware that JSON/YAML serializers require special handling to understand NaN.   Unknown to me whether any NaNs are being serialized at this time.   A Java7-friendly alternative would be to use nullable values rather than special values.

**Comment by EronWright** [comment]
My proposal is to remove the obsolete elements, and eliminate the `NeuralNetConfiguration:: overRideFields` method .

**Comment by EronWright** [comment]
The work is happening on bugfix-535 branch.    Each commit corresponds to an obsolete property removed.
https://github.com/deeplearning4j/deeplearning4j/commits/bugfix-535
