### ISSUE TITLE
Vector inference from DL4J library is different than gensim for the same data

### ISSUE THREAD

**Issue by legalizenet** [deeplearning4j/deeplearning4j#5460]
I have written a simple code that reads GoogleNews model and try to infer vectors for labels/words . The result I see is very different than the original code that was written in python/gensim. This difference is causing everything downstream not work (e.g. downstream I do averaging of the vector for a given text and then doing dot product against another w2v model to calculate similarity). With Python code results are quite accurate, so I’m taking that as a baseline. So when java/DL4j returns different vector values for the same words , against the exact same GoogleNews model , I’m kind of stuck at this point. Any help is appreciated to find out why am I seeing such a big difference in vector array values. Here is the gist for all for your reference.

Python/Gensim Code that does word vector inferencing  
> https://gist.github.com/legalizenet/6c60144d2b6d03407f54a142d311b3b5

Word vectors output from python code 
 > https://gist.github.com/legalizenet/8e6162f395fa522a8fdcb40dca4dd3f6

Java/DL4j code that does word vector inferencing 
 > https://gist.github.com/legalizenet/476e1f2bacb377c22d9556dd30ce7b84

Word vector output from java/DL4j Code 
  > https://gist.github.com/legalizenet/e68e7cf0619a5d04d703a7aeb0e952a8

Pre-trained Google News Word2Vec model was downloaded from  
 > https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing

**Comment by raver119** [comment]
Thanks for highlighting this, it's not a single problem it's two minor problems.

1) By default there's normalization applied on load, and there's no way to change that.
2) There's linebreaks used, which can't be turned off - that causes vocab shitft.
3) And you can't use appropriate method manually, since it's protected. 

So, i've fixed these issues in my branch and will merge later.
For now you could use Java reflection and use protected WordVectorSerializer.readBinaryModel() method. Or you could use snapshots once they are rebuilt.

**Comment by rajeshetty** [comment]
So the problem is when the GoogleNews model is read and not when I tried to get vector for given word- right?. So questions are
1. WordVectorSerializer.readBinaryModel()  would solve the issue of inferencing incorrect vector ?
2. When will be snapshots built, is there any way for me to get notified when that happens, so that I can pull a specific version/branch ?. 
3. When will this code gets merged to master?

**Comment by legalizenet** [comment]
So the problem is when the GoogleNews model is read and not when I tried to get vector for given word- right?. So questions are
1. WordVectorSerializer.readBinaryModel()  would solve the issue of inferencing incorrect vector ?
2. When will be snapshots built, is there any way for me to get notified when that happens, so that I can pull a specific version/branch ?. 
3. When will this code gets merged to master?


Thanks for looking at this so quick.

**Comment by raver119** [comment]
1) yes. just use proper params there.
2) No idea. Usually that happens daily, but not sure how it works right now.
3) 30 minutes ago.

**Comment by saudet** [comment]
Snapshots are built at least once daily. There's no notifications, but we might be able to let people access the dashboard, @sshepel?

**Comment by legalizenet** [comment]
I quickly looked at the code for existing readWord2VecModel() which internally uses readBinaryModel() , if I directly use readBinaryModel() instead of readWord2VecModel(), would not I be bypassing lot of that code, off course I have not looked the code in detail what it does exactly. Can you confirm ?

**Comment by raver119** [comment]
That's what happens for your file anyway.

**Comment by legalizenet** [comment]
Java reflection comes with performance overhead , seeing this is a model load which can be done on JVM start/boot time,  then it should be ok and not too bad, unless and until I see any issue . Will keep you posted . 

Also I do see 
                   if (originalPeriodic)
                        Nd4j.getMemoryManager().togglePeriodicGc(true);

                    Nd4j.getMemoryManager().setOccasionalGcFrequency(originalFreq);

Do I need that ?

**Comment by legalizenet** [comment]
Ok. That did the trick. Here is the code.
 
```
File gModel = new File("/word2vec/GoogleNews-vectors-negative300.bin.gz");
Method method = WordVectorSerializer.class.getDeclaredMethod("readBinaryModel", File.class, boolean.class , boolean.class);
method.setAccessible(true);
Word2Vec w2v = (Word2Vec)method.invoke(null, gModel, false, false);
```

Now I see vector values almost similar to gensim model vectors.

Can you confirm if I need to do following right before "readBinaryModel" reflection code ?

```
if (originalPeriodic)
{
      Nd4j.getMemoryManager().togglePeriodicGc(true);
}
Nd4j.getMemoryManager().setOccasionalGcFrequency(originalFreq);
```

**Comment by raver119** [comment]
1) They are not "almost similar", they are equal.
2) If you aren't sure in any methods - you can check javadocs.  But i guess these calls are not required for you.

**Comment by sshepel** [comment]
> Snapshots are built at least once daily. There's no notifications, but we might be able to let people access the dashboard, @sshepel?

@saudet, you are right, snapshots a build on daily bases, and when build is failing or get back to green user will be notified. Which means, if you follow the link from e-mail you can see all activities related to repository.

Dashboard that we had is not useful anymore, because we do have one project basically...

**Comment by sshepel** [comment]
@saudet , sorry, maybe you got me wrong but we already have that from native Jenkins UI.
Here: http://master-jenkins.skymind.io:8080/blue/organizations/jenkins/deeplearning4j%2Fdeeplearning4j/activity/
BTW, this link (job path) will be changed these days, will let you know.

**Comment by saudet** [comment]
@sshepel It doesn't work for people outside of the Deeplearning4j organization, it asks for GitHub credentials.

**Comment by sshepel** [comment]
Ok, will check that...
