### ISSUE TITLE
ND4J array copy performance

### ISSUE THREAD

**Issue by smpawlowski** [deeplearning4j/deeplearning4j#5545]
Micro benchmark below compares array copy performance between double[] and ND4J.
https://gist.github.com/smpawlowski/33d392969ea8f05cb08eac6081887c57

Output is like this:
Benchmark                           (arraySize)  (iterations)   Mode  Cnt       Score   Error  Units
Nd4jOpsBenchmark.arrayCopy                   30           500  thrpt    2   45472.169          ops/s
Nd4jOpsBenchmark.arrayCopyInPlace            30           500  thrpt    2  287244.954          ops/s
Nd4jOpsBenchmark.nd4jCopy                    30           500  thrpt    2     535.974          ops/s
Nd4jOpsBenchmark.nd4jCopyInPlace             30           500  thrpt    2    1688.383          ops/s
Nd4jOpsBenchmark.nd4jCopyInPlaceWs           30           500  thrpt    2    1661.200          ops/s
Nd4jOpsBenchmark.nd4jCopyWs                  30           500  thrpt    2     994.290          ops/s

Throughtput of ND4J copy is much lower than double[].
arrayCopyInPlace which calls System.arraycopy(x, 0, y, 0, x.length) scores 287,244 ops/s
nd4jCopyInPlace which calls Nd4j.copy(x, y) scores 1,688 ops/s

<rl4j.version>1.0.0-beta</rl4j.version>

Number of threads used for NativeOps: 12
Number of threads used for BLAS: 12
Backend used: [CPU]; OS: [Windows 10]
Cores: [48]; Memory: [26.7GB];
Blas vendor: [MKL]

Could you advise if this is expected or how this kind of operation could be improved?

**Comment by raver119** [comment]
Sorry to say that, but all your tests aren't right.

Nd4j.copy() or INDArray.dup() methods aren't the same as System.arraycopy(). 
If you want to compare against arraycopy - use Pointer.memcpy() or corresponding MemoryManager methods. Keep in mind - INDArrays store stuff in off-heap. So, pointers, memset, memcpy, vectorization - that's what rocks here.

If you want to compare against java methods like array[x] = y - there won't be realistic way to compare that on java level for us - because array[x] is primitive, and Nd4j methods are not. So when you call, INDArray.getScalar() or INDArray.putScalar() - that's not even close to jvm heap access over primitives. There will be other methods executed before actual memory access: boundaries will be checked, memory properties will be investigating, coordinates will be established (if needed) etc.

So there's kind of useless comparison here. If you're able to write anything significant based on primitives only - you have my endless respect, and you probably don't need explanations above. Otherwise - we do the same as you would do: before accessing memory - we do necessary checks, validate arguments etc.

**Comment by saudet** [comment]
Known issue with small arrays, see https://github.com/deeplearning4j/nd4j/issues/1189.
