### ISSUE TITLE
Issue storing then displaying stats

### ISSUE THREAD

**Issue by nlebreton** [deeplearning4j/deeplearning4j#5611]
Hi, I would like to watch the stats of a training session. They were saved in a file using FileStatsStorage. I then used UIServer, but no stat is displayed in the browser.

The following errors are displayed in the web console:

Erreur dans les liens source : SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
TypeError: data.memory[machineID] is undefined

Code snippets and logs: https://gist.github.com/nlebreton/fde547a86150dc052465c440185ae08e

Deeplearning4j: 1.0.0-beta
Training on ubuntu / browsing stats on Window 10 / Firefox
Java 1.8 on both

**Comment by nlebreton** [comment]
Here is a link to the pom content and the project dependencies:

https://gist.github.com/nlebreton/5baec5b7b0ba65991764fbe099c056ed

**Comment by nlebreton** [comment]
Here is the zipped stats file:
[training-stats.zip](https://github.com/deeplearning4j/deeplearning4j/files/2107972/training-stats.zip)

**Comment by AlexDBlack** [comment]
Thanks. Nothing looks off in your pom.xml or in dependency tree either... odd.
However, the training stats file you have provided seems to be empty.

Can you post more of your code? Maybe there's something else there that would explain this.

**Comment by nlebreton** [comment]
Here is a link to the code.

https://gist.github.com/nlebreton/768164b798b98f084f2ac7374f924f20

**Comment by AlexDBlack** [comment]
OK, there we go:
https://gist.github.com/nlebreton/768164b798b98f084f2ac7374f924f20#file-gistfile1-txt-L185-L186

note the method name: *set*Listeners... there's also an *add*Listeners.
So the second time you call it, you're overwriting the first listener.
So, just call ```modelTransfer.setListeners(new StatsListener(statsStorage), new ScoreIterationListener(batchSize));``` instead

So the exception you are getting is really just a lack of validation when no data is available. Which is something we should fix, but not the actual problem here :)

**Comment by nlebreton** [comment]
Obvious and under my eyes. You're right, the actual problem is that I need a coffee to wake up. :)
