### ISSUE TITLE
Unit tests are failing for nd4j-kryo on linux-x86_64 and CUDA 8.0,9.0,9.1 backend

### ISSUE THREAD

**Issue by sshepel** [deeplearning4j/deeplearning4j#5848]
For more details please see the gist.
https://gist.github.com/sshepel/a81d0f3b7e18043454986b5970fe82a5

**Comment by agibsonccc** [comment]
This seems rather random: Caused by: java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.2-edc3f43a-0653-4131-9f66-3396e19c5043-libsnappyjava.so: /tmp/snappy-1.1.2-edc3f43a-0653-4131-9f66-3396e19c5043-libsnappyjava.so: failed to map segment from shared object: Operation not permitted


This looks to be possibly permissions related? Are you sure this isn't just a CI hiccup?

**Comment by sshepel** [comment]
Ok, will double check that, thanks for pointing that...

**Comment by saudet** [comment]
@sshepel Looks like an issue related to Docker: https://github.com/docker/compose/issues/1339

@johanvos @kevinrushforth See, this looks like another case of one more guy reinventing the wheel, trying to make another native loader as with https://github.com/javafxports/openjdk-jfx/pull/83, instead of cooperating together to come up when a solution that works well!

**Comment by sshepel** [comment]
@saudet, right, as I said above, I didn't noticed that, and once Adam point me that line in log, I did some fixes in CI scripts, but it didn't help... Will proceed with debuging...

**Comment by sshepel** [comment]
Fixed in CI scripts.
