### ISSUE TITLE
SameDiff: matmul op needs to support multiple batch dimensions (rank 4+ input)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6189]
https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/blas/matmul.cpp
https://www.tensorflow.org/versions/r1.8/api_docs/python/tf/matmul

Another op we need adjusted for TF import.
We support rank 2 and 3 inputs (the latter being the "batch" case) but TF also supports rank 4+ (I've tried up to and including rank 5) as a batch case.
The basic idea is the same: for the rank 4/5 cases: the 2/3 leading dimensions are the batch.
so [a,b,3,4]*[a,b,4,5] gives [a,b,3,5] output

**Comment by shyrma** [comment]
Hi Alex

Are you sure this problem is still relevant ?
below are c++ tests which show the possibility of matmul to work with rank=4 (for >4 should work as well) :

https://github.com/deeplearning4j/deeplearning4j/blob/7ed730a1dc25202f57c8ec952e3266948df6a4ae/libnd4j/tests_cpu/layers_tests/DeclarableOpsTests9.cpp#L664-L711

https://github.com/deeplearning4j/deeplearning4j/blob/7ed730a1dc25202f57c8ec952e3266948df6a4ae/libnd4j/tests_cpu/layers_tests/DeclarableOpsTests9.cpp#L839

**Comment by AlexDBlack** [comment]
Hm, looks like you're right.
I misread the stack trace when posting the issue: on review, it seems that the failure is actually due to bad shape calculation at the Java level, not the c++/libnd4j level.
