### ISSUE TITLE
Failing deconv + locally connected tests

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#6258]
Recently introduced by me :/
```
Failed tests: 
  CNNGradientCheckTest.testDeconvolution2DUnsupportedSameModeLayer Expected exception: java.lang.IllegalArgumentException
Tests in error: 
  CNNGradientCheckTest.testDeconvolution2DUnsupportedSameModeNetwork ?  Unexpect...
  LocallyConnectedLayerTest.test1dForward:109 ? IllegalState Cannot create gradi...
```

**Comment by AlexDBlack** [comment]
The latter one is due to some new validation I recently added (though it's a legit issue).
https://github.com/deeplearning4j/deeplearning4j/blob/b232e19eb2bc734c5c29bbf992136291a4791ef1/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/LocallyConnected1D.java#L198-L201
We don't want to create the zeros here for the 'has bias' case.
