### ISSUE TITLE
About LossMSE

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#6395]
https://en.wikipedia.org/wiki/Mean_squared_error
MSE = sum { (y - yLable) ^ 2} / n
here n looks is the number of data(features or labels)

But I find the LossMSE implement:

    @Override
    public double computeScore(INDArray labels, INDArray preOutput, IActivation activationFn, INDArray mask, boolean average) {

        double score = super.computeScore(labels, preOutput, activationFn, mask, average);
        score /= (labels.size(1));
        return score;
    }

the "super" is LossL2,my question is, why does the socre div by lable.size(1)?
I think it's should be label.size(0).
(We know the label shape is (batchSize, columnOfLabel), shoud div by batchSize

I know it can get the finnal correct result(classification ect.) by using lable.size(1), 
But it look strange.

**Comment by liweigu** [comment]
My opinion:
Score with LossL2 is the sum of error of each element (along size(1)) , and score with MSE is avarage of them.
Besides, in the computeScore method in LossL2, there's the code for division by size(0):
if (average)
	score /= scoreArr.size(0);

**Comment by AlexDBlack** [comment]
Yes, @liweigu is exactly right. The division by minibatch size (label.size(0)) is in LossL2

**Comment by AlexDBlack** [comment]
Yes, I closed it. I'm quite sure it's correct.

> U can do a test, if the labels have 1 column, results of LossL2 and LossMSE are same,
is it reasonable?

Yes, that's totally reasonable and expected. for N=1 case, sum(squared_difference) and mean(squared_difference) are the same thing.

> The last parameter is fixed false!!!

That's correct, and that should be the case. It is misleading when reading this in isolation, however.
https://github.com/deeplearning4j/deeplearning4j/blob/9cab47ab04e21c44696802f7bf7d21ecaf451645/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/BaseOutputLayer.java#L90-L94

Take a look at the code at the above link. You'll see the division by minibatch size at line 94. The reason it's hard-coded to 'false' is that we use that code for CNNs and RNNs via reshaping.
Consider an RNN with input of 3 examples and 10 time steps. We reshape from [3, nOut, 10] to [30, nOut] and pass to loss function. So it looks like 30 examples to loss function, but it's actually 10.
Line 94 divides by the correct minibatch size (10) instead of labels.size(0)=30.
This is by design: we do want to add the outputs for RNNs, not average them.
