### ISSUE TITLE
DL4J eating up all memory

### ISSUE THREAD

**Issue by DanielWieczorek** [deeplearning4j/deeplearning4j#6647]
I'm building a setup where I train a RNN using CUDA with a relatively long time series (1441 steps) and then doing predictions using the CPU. Training is working fine and the memory consumption is alright. Here's how the network is built:

	MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder().seed(seed).updater(new Adam(2e-2)).l2(1e-5)
		.weightInit(WeightInit.XAVIER).gradientNormalization(GradientNormalization.ClipElementWiseAbsoluteValue)
		.gradientNormalizationThreshold(1.0).trainingWorkspaceMode(WorkspaceMode.ENABLED)
		.inferenceWorkspaceMode(WorkspaceMode.ENABLED)
		.list().layer(0, new LSTM.Builder().nIn(vectorSize).nOut(128).activation(Activation.TANH).build())
		.layer(1, new LSTM.Builder().nOut(512).activation(Activation.TANH).build())
		.layer(2, new DenseLayer.Builder().nOut(512).activation(Activation.RELU).build())
		.layer(3,
			new RnnOutputLayer.Builder(LossFunctions.LossFunction.MSE).activation(Activation.IDENTITY)
				.l2(0.0001).weightInit(WeightInit.XAVIER).nOut(1).build())
		.pretrain(false).backprop(true).backpropType(BackpropType.TruncatedBPTT).tBPTTBackwardLength(60)
		.tBPTTForwardLength(60).build();

	MultiLayerNetwork net = new MultiLayerNetwork(conf);
	net.setListeners(new PerformanceListener(1, true));
	net.setCacheMode(CacheMode.DEVICE);
	net.init();

Every few periods the trained network is stored to a file where the other app can use it for prediction. The whole purpose is to train the network on my PC at home with a powerful graphics card and then run the predictions on a server on the CPU.  

When I do this, the app doing predictions is eating up all the memory available and does not seem to complete its task. Enabling settings to run the GC regurlarly does not seem to help.

I prepared a little demo app here: [https://github.com/DanielWieczorek/dl4j-memory](https://github.com/DanielWieczorek/dl4j-memory).

Here's the stacktrace:

`
Exception in thread "main" java.lang.OutOfMemoryError: Failed to allocate [4252633088] bytes
        at org.nd4j.linalg.cpu.nativecpu.CpuMemoryManager.allocate(CpuMemoryManager.java:49)
        at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.alloc(Nd4jWorkspace.java:415)
        at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.alloc(Nd4jWorkspace.java:315)
        at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:656)
        at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:58)
        at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:261)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1492)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.leverageTo(BaseNDArray.java:6091)
        at org.nd4j.linalg.workspace.BaseWorkspaceMgr.leverageTo(BaseWorkspaceMgr.java:188)
        at org.deeplearning4j.nn.workspace.LayerWorkspaceMgr.leverageTo(LayerWorkspaceMgr.java:78)
        at org.deeplearning4j.nn.layers.AbstractLayer.setInput(AbstractLayer.java:116)
        at org.deeplearning4j.nn.layers.AbstractLayer.activate(AbstractLayer.java:258)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1192)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2269)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2232)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2224)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2205)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2287)
        at AbstractNeuralNetworkPredictor.predict(AbstractNeuralNetworkPredictor.java:23)
        at Main.main(Main.java:8)
`

All this occured on Windows 10, with Java 8.

Would be cool if we could find a solution to this.

Kind regards

Daniel

**Comment by AlexDBlack** [comment]
OK, so a few things here.
First: Make sure you aren't causing a memory leak by keeping array references around once you no longer need them.
We've yet to see an instance where memory isn't released once arrays (not using workspaces) are cleaned up by the JVM.
So if CG doesn't help, this is a possible cause.

Second: Consider using these methods instead of output:
https://github.com/deeplearning4j/deeplearning4j/blob/87167e91c616584a296abe637d408a8efd9e05b7/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L2251-L2308
Output arrays during inference are normally detached (not in a workspace) but the consequence is that memory will only be released once they are garbage collected.
Those methods I linked will keep the arrays in a workspace and hence they don't need to be GC'd before memory can be reused.

Third: I'm not seeing your neural network configuration in your code - but the amount of memory being allocated suggests there may be some issues there. Can you share it?
(I mainly need number of layers, layer sizes, and input/output sizes)
> Failed to allocate [4252633088] bytes

That's around 4GB, which is a lot for 1441 steps.

**Comment by DanielWieczorek** [comment]
These are some good remarks. I'll implement them when I have time. 

The code for training the model is [here](https://github.com/DanielWieczorek/RSS-Grabber/blob/master/rss-advisor-training/src/main/java/de/wieczorek/rss/advisor/business/TradingNeuralNetworkTrainer.java).

In the demo project I only put the stuff which was actually needed to reproduce the error. The file "net" in the root directory is the persisted trained network generated by code linked above.

Funny this is, it tried to allocate 4GB when it already had 8-10GB. 

In the same project I have another net where these problems do not occur [here](https://github.com/DanielWieczorek/RSS-Grabber/blob/master/rss-insight-training/src/main/java/de/wieczorek/rss/insight/business/RssSentimentNeuralNetworkTrainer.java).

I suspect that I maybe some values are messed up during saving or reading the file and then some infinite loop tries to allocate memory. At least that is how it looks from the outside.

**Comment by AlexDBlack** [comment]
Hm... so your model isn't that large, though perhaps the batch size is contributing here (for example the activations for the LSTM layer is about 720mb alone (256 batch x 512 layer x 1441 steps x 4 bytes for FP32).

Mind running a few iterations of training/inference and then running this with inputType.recurrent(vectorSize) - and then sharing it in a gist here: https://gist.github.com/ :

https://github.com/deeplearning4j/deeplearning4j/blob/87167e91c616584a296abe637d408a8efd9e05b7/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L3590-L3602

> I suspect that I maybe some values are messed up during saving or reading the file and then some infinite loop tries to allocate memory. At least that is how it looks from the outside.

No, that's extremely unlikely.

**Comment by AlexDBlack** [comment]
Yeah, so that memory use doesn't look to bad.
And yes, a 1441 minibatch size for inference will use a lot of memory, especially for a RNN :)

> I'm a newbie to neural networks, but what would be the use case for using batches for inference?

Performance, mainly. It's faster (for example) to do 1x output call with a batch size of 50, than 50x output calls with a batch size of 1. That's mainly due to the way in which operations are parallelized at the c++ level for both CPUs and GPUs - we can get better hardware utilization with larger batches.
Batch inference is used a ton for non-realtime data/applications.

I'll close this as resolved.
