### ISSUE TITLE
Better Test resources management

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#6667]
Right now we are starting to hit the size limit for jar files. We need to look in to how to better implement a get resources api or something similar for tests.

Right now, we just have a compression flag for dl4j-test-resources.

Aha! Link: https://skymindai.aha.io/features/DL4J-51

**Comment by AlexDBlack** [comment]
More background: when the dl4j-test-resource JAR is 4gb or larger, many resources are just not found even though they clearly exist and are on the classpath.
Uncompressed with Git LFS installed: we're over this 4gb now. 
Default is uncompressed: https://github.com/deeplearning4j/dl4j-test-resources/pull/144
But it's configurable via system property.

Why default to uncompressed? Because it's a bottleneck for some workflows (2:40 vs 0:40 on my machine, and would be worse now - with >10 builds per day of this when I was doing TF import testing)

What we need:
1. A solution to the 4GB ClassPathResource limitation, OR
2. A better long term solution than use a JAR for this

One simple solution I've been using, rather than dumping another 2+GB for SameDiff TF models is basically this:
https://github.com/deeplearning4j/dl4j-test-resources/blob/master/src/main/resources/tf_graphs/zoo_models/deeplab_mobilenetv2_coco_voc_trainval/tf_model.txt
https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/imports/TFGraphs/TFGraphTestZooModels.java#L62-L124
Essentially, that just looks for the .txt file, parses address and MD5 from it, downloads resources on demand and caches them in ```{user.home}/.nd4jtests```
It's a simple approach, but might be something we could use for other large resources.
