### ISSUE TITLE
Purpose of viewArray attribute of IUpdater.instantiate

### ISSUE THREAD

**Issue by nadheesh** [deeplearning4j/deeplearning4j#6716]
I see that whenever, we instantiate a GradientUpdater, we need to provide a viewArray with appropriate size to store the state of the gradient updater. However, the Gradient updaters do not allow retrieving the updated view array (unless we use updater specific code to combine their parameters to construct the view array).  

So what is the purpose of that attribute?

**Comment by AlexDBlack** [comment]
OK, so first thing: Most users should never need to instantiate these manually/directly.
Based on your previous issue, I can assume you are using SameDiff, which (as of 1.0.0-beta3) properly supports training.
If that's all you care about: upgrade to 1.0.0-beta3, and take a look at this.
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/samediff/training/SameDiffTrainingExample.java

If you are doing something completely custom (not just training a DL4J or SameDiff net): then many of the GradientUpdaters have state/history used in the calculation of updates.
The view array is used so that we can have different segments of 1 array shared amongst different updater instances.
For example, say you have 2 layers, 10 parameters each, using Adam updater (which has state size 2* numParams).
20 params total, 2*20 = 40 values for the updater state. The first layer would get the first 20 values from the full array, second layer would get next 20.

As for not retrieving the updater state: generally it's stored externally. You'll note that both DL4J and SameDiff store the full array, and not the views/subsets that are passed to the updaters.
In principle we could add a getter - I see no hard in doing so (feel free to send us a pull request) but we've never needed it so far.

**Comment by nadheesh** [comment]
> As for not retrieving the updater state: generally it's stored externally. You'll note that both DL4J and SameDiff store the full array, and not the views/subsets that are passed to the updaters.

Does this mean, that the array being passed to the updater, is always modified internally. So that if we maintain a pointer to the initial view array, that is also the updated view array after each training iteration?
If so then it make sense for not having a getter. I should have debugged and check the arrays. 

Thanks for the help @AlexDBlack

**Comment by AlexDBlack** [comment]
> the array being passed to the updater, are always modified internally

Yes, exactly. It's always modified in-place, never replaced by a new array or anything.
