### ISSUE TITLE
New version of BPTT for Information Retrieval

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#700]
http://arxiv.org/pdf/1502.06922.pdf

Would be a great recurrent net to add to the lineup.

**Comment by gowthamnatarajan** [comment]
I have the following question in the paper.
I am implementing the RNN version of this paper (not LSTM). So, the only change in the algorithm on page 5 is that instead of using eq 14 to 44, I will be using 9 to 12.

I am surprised that the number of time steps unfolded in BPTT has to be the same for query and document (equation 9 to 11). Because the document is usually longer than the query.

**Comment by AlexDBlack** [comment]
OK, so I've had a bit of a read through the first few pages of the paper.
I'm not going to suggest I understood all of it (or even a lot of it :P), but my basic understanding is as follows:
Do sentence -> semantic vector, where semantic vector is just RNN activations at final time step
Work out semantic vector for query and document (standard forward pass)
Use cosine similarity of semantic vectors between query and document

Goal is to train RNN to produce similar semantic vectors for query and document for positive samples (i.e., positive query + document click on pairs). And I guess minimize the cosine similarity for negative samples (query + document not clicked on pairs)? Not sure on that last part.

So re: bptt lengths, it seems reasonably clear to me that they are doing full forward pass on both the query and document (i.e., equation 3). Two possibilities come to mind:
- In truncated BPTT sometimes the forward pass and backward pass lengths are different: i.e., might do forward pass for 500 time steps but backward pass for only 100 time steps. See for example http://www.cs.utoronto.ca/~ilya/pubs/ilya_sutskever_phd_thesis.pdf pg23. Perhaps this is what they mean?
- In algorithm 1, they have "Maximum sequence length for truncated BPTT "T"". Maybe it's implied somewhere that some of the terms are zero for certain values of tau in algorithm 1? i.e., beyond end of query or document we're just summing zeros, and effectively sum over entire document and query even though T is the same for both.

**Comment by gowthamnatarajan** [comment]
Thanks!
Consider update equation (9).
They include both yQ(t - tau - 1) and yD(t - tau - 1), but since document is longer than query most of the time, I was thinking that I can only back propagate the length of the query. But, what you are suggesting is to continue backpropagating till the end of the document and yQ(t - tau - 1) would be zero? This also seems interesting. Thanks. Will run the code and see if the results are good. Thanks again!.

Also, in Algorithm 1 there are 2 summation terms (tau from 0 to T). One for query and the other for document. Assume we are using eq (9). Since the numerator of the derivative term is the same, if the Wrec matrix is initialized the same for both query and document won't both the update have the same value? So Wrec matrix would be the same for the Query RNN and document RNN. Is that ok?
