### ISSUE TITLE
DL4J: FileDataSetIterator performance issue?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7101]
From gitter: AndresCubides @AndresCubides 02:39
```
@AlexDBlack I used the performance Listener and with both iterators ETL is the same ETL = 0 ms, but the iteration time do changes incredibly with the ListDataSetIterator Iteration time = 15 ms but with FileDataSetIterator Iteration time = 79703 ms. And i'm using the same dataset here I paste the only piece of code I changed:
ListDataSetIterator Code:
DataSet dataSet = new DataSet(inputs, outputs);
List<DataSet> listDs = dataSet.asList();
Collections.shuffle(listDs);
net.setIterator(new ListDataSetIterator(listDs, batchSize));

FileDataSetIterator Code:
DataSet dataSet = new DataSet(inputs, outputs);
dataSet.shuffle();
new File(train_path).mkdirs();
File datasets = new File(train_path+"train.bin");
dataSet.save(datasets);
net.setIterator(new FileDataSetIterator(new File(train_path), batchSize));
```

**Comment by treo** [comment]
@AndresCubides 
there are a few things:

1. You should be using 1.0.0-beta3
2. It looks like you are writing a single dataset of 116 million examples to your disk - I guess your performance issues may be due to reading this one huge file

try writing your datasets like this to disk:

```java
//[...]
DataSetIterator iter = new ListDataSetIterator(listDs, batchSize);

int i = 0;
while(iter.hasNext()) iter.next().save(new File(train_path+"train-"+(i++)+".bin"))
```

That will create 116000000/batchSize files - but don't worry, if you want to change your batch size on reading, the reader will do the necessary work to get either multiple batches out of it, or span a batch over multiple files if needed.

**Comment by AndresCubides** [comment]
@treo I'm not using 1.0.0-beta3 because I ran different models with that version and the performance of the models dropped substantially, not sure if not using .backprop(true) in the update or something else affected the result but with 1.0.0-alpha the models have a good performance.

I ran one model with ListDataSetIterator and another with FileDataSetIterator as a test to see why is the time difference so big because I actually need to train a Net with two inputs so I'm planning to use FileMultiDataSetIterator, I already tried it but I have the same issue, is taking too long.
Does this while configuration to save the dataset works also with FileMultiDataSet?

Thank you so much for the help.

**Comment by treo** [comment]
Yes, the main thing I want you to try is to just not have one enormous DataSet object, but instead lots of rather small ones (ideally exactly the batch size you are using).

**Comment by AlexDBlack** [comment]
Right, the whole point of FileDataSetIterator is for reading *multiple* 
The "one single DataSet" use case isn't something we'd recommend or optimize for (mainly because having all your data in memory is unnecessary and is a terrible idea in general due to the memory requirements). That said, we *might* be able to improve the performance for this case in FileDataSetIterator, though I wouldn't consider it a priority.

> @treo I'm not using 1.0.0-beta3 because I ran different models with that version and the performance of the models dropped substantially, not sure if not using .backprop(true) in the update or something else affected the result but with 1.0.0-alpha the models have a good performance.

That's news to me, and we haven't had any reports of a performance degradation.
And no, .backprop(true) isn't relevant here (it's always been the default anyway).
Can you open an issue with further details? I'm happy to look into this in more detail, but I don't have anything to go on at this point...

**Comment by AndresCubides** [comment]
@treo @AlexDBlack Thank you very much for the help, saving the datasets in small chuncks using the while helped, the iteration time did decrease substantially but not enough so at the end I created a MultiDataset Iterator based in ListDataSetIterator. 

@AlexDBlack Regarding the performance degradation when I updated, I don't have much information sorry, I was in a hurry and when I downgraded it, the modeling worked well again, there wasn't much change in the code I remember besides the pretrain and backprop I also had to change:
.trainingWorkspaceMode(WorkspaceMode.SEPARATE)
.inferenceWorkspaceMode(WorkspaceMode.SINGLE)

I could try updating again and doing some test to have more information for you but in a couple of weeks cause right now I'm really short on time.

Again thank you so much for the help.

**Comment by AlexDBlack** [comment]
OK, thanks for the update.
I'll close this then - my experience in the past is that for most nets data loading is not a problem with FileDataSetIterator when used with multiple saved DataSet objects (i.e., loading time is less than iteration time, so it's hidden by the fact that we use async prefetch). Profiling and trying to optimize this for the "huge single DataSet" edge case isn't a priority.
