### ISSUE TITLE
ND4J: some CUDA reductions not using dimension during execution

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7384]
#### Issue Description

Trying to use a reshape operation with a -1 value will have that -1 be set to 0, and then throw an error because one of the dimensions is 0.

This only seems to happen for me after a `sum()` op.

To reproduce:
```java
@Test
public void test(){
    SameDiff SD = SameDiff.create();
    SDVariable in = SD.one("test", 5, 8, 3, 4);
    SDVariable out = in.reshape(-1, 4);
    SDVariable out1 = out.reshape(4, 15, -1);
    SDVariable out2 = SD.sum(out1, true, 2);

    SDVariable out3 = out2.reshape(-1, 4);  // <----  error here

    System.out.println(Arrays.toString(out3.eval().toFloatMatrix()));

}
```
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-SNAPSHOT
* platform information (OS, etc). Windows
* CUDA version, if used. 10.0

**Comment by rnett** [comment]
Using `dot` also surfaces the bug, it does not seem to be dependent on `sum`.

```java
@Test
public void test(){
    SameDiff SD = SameDiff.create();
    SDVariable in = SD.one("test", 5, 8, 3, 4);
    SDVariable out = in.reshape(-1, 4);
    SDVariable out1 = out.reshape(4, 15, -1);
    SDVariable out2 = SD.dot(out1, out1, 2);

    SDVariable out3 = out2.reshape(-1, 4);  // <----  error here

    System.out.println(Arrays.toString(out3.eval().toFloatMatrix()));

}
```

**Comment by rnett** [comment]
More testing:  even if you don't use -1, you get a NPE.
See:
```java
@Test
public void test() {
    SameDiff SD = SameDiff.create();
    SDVariable in = SD.one("test", 5, 8, 3, 4);
    SDVariable out = in.reshape(-1, 4);
    SDVariable out1 = out.reshape(15, -1);
    SDVariable out2 = SD.mmul(out1, SD.transpose(out1));
    System.out.println(Arrays.toString(out2.eval().shape()));
    SDVariable out3 = out2.reshape(5, 45);  // <----  error here

    System.out.println(Arrays.toString(out3.eval().toFloatMatrix()));

}
```

Comes from the same place as #7381, I'm going to close this.

**Comment by rnett** [comment]
This should not be closed.  The test that caused me to close it was bad.

**Comment by AlexDBlack** [comment]
OK, looks like the cause is java level, CudaExecutioner... we end up here:
https://github.com/deeplearning4j/deeplearning4j/blob/7719b1af0498c04d5e311043637b3757a2e7d222/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/linalg/jcublas/ops/executioner/CudaExecutioner.java#L650-L662

The reason it fails is due to that sum being treated as full array reduction due to dimension, because of the incorrect null dimension. It looks like the reshape fails because of lack of validation: we're trying to reshape the scalar to [-1, 4]
Now, we could just get dimension as int[] and pass here... but we're using INDArray now for dimension internally, so it would be more efficient to avoid the object creation and use the buffer directly.


Unrelated: there's a bunch of old [1,1] shapes here...
https://github.com/deeplearning4j/deeplearning4j/blob/7719b1af0498c04d5e311043637b3757a2e7d222/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/linalg/jcublas/ops/executioner/CudaExecutioner.java#L549
