### ISSUE TITLE
java.lang.NoSuchMethodError: org.nd4j.linalg.indexing.NDArrayIndex.interval(IIZ)

### ISSUE THREAD

**Issue by sayadyan** [deeplearning4j/deeplearning4j#7590]
#### Issue Description

Exception:
`
java.lang.NoSuchMethodError: org.nd4j.linalg.indexing.NDArrayIndex.interval(IIZ)Lorg/nd4j/linalg/indexing/INDArrayIndex;
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:699)
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:600)
`

This change introduced the issue in MultiLayerNetwork.
https://github.com/deeplearning4j/deeplearning4j/commit/f977889aadaa9d9e36a088c4a4f8fd3c1b7ff72d#diff-a326034760abf91c41121b33f9fec2d3R658

#### Version Information

Using latest snapshots for dl4j/nd4j.

**Comment by AlexDBlack** [comment]
This is almost certainly due to mismatched DL4J and ND4J snapshots - i.e., new ND4J snapshots with old DL4J snapshots.
I can confirm there are no build issues on current master; however the latest snapshots look to be out of date (a few days ago): https://oss.sonatype.org/content/repositories/snapshots/org/deeplearning4j/
cc @sshepel 

In the mean time, if you need a quicker workaround, you should be able to clone the DL4J mono repo, cd into deeplearning4j directory, and do a "maven clean install -DskipTests"

**Comment by sayadyan** [comment]
@AlexDBlack Thanks for the reply!

**Comment by sshepel** [comment]
@sayadyan @AlexDBlack, snapshots should be in sync now.
