### ISSUE TITLE
SameDiff: Duplicate name validation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7705]
This should throw an exception. I thought we already had validation for this, but apparently not.

```
SameDiff sd = SameDiff.create();
SDVariable x1 = sd.placeHolder("input", DataType.FLOAT, 5, 3);
SDVariable x2 = sd.placeHolder("input", DataType.FLOAT, 5, 3);
```

**Comment by Charele** [comment]
Hmmm, I write a simple linear regression app using SameDiff,
I use identity activation, but I can't use this code:
val activations = sd.nn().identity(x.mmul(W).add(b0))
There's no idetity() method in SDNN class.
I add them into SDNN.java manually: 

    public SDVariable identity(SDVariable x) {
        return sigmoid(null, x);
    }
    public SDVariable identity(String name, SDVariable x) {
        validateFloatingPoint("identity", x);
        SDVariable result = f().identity(x);
        return updateVariableNameAndReference(result, name);
    }

Is it correct?

I can't ensure because I got a bad result from my linear regression program:-(

**Comment by AlexDBlack** [comment]
Fixed here, and merged to dev branch; will be merged from dev branch to master soon: https://github.com/deeplearning4j/deeplearning4j/pull/7774

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/7792
