### ISSUE TITLE
puzzling BaseDataBuffer's hashCode() method

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#7765]
@Override
    public int hashCode() {
        int result = (int) length;
        result = 31 * result + (allocationMode != null ? allocationMode.hashCode() : 0);
        return result;
    }
Maybe sometime we need this special hashCode(),
but it lets some result become strange:

  val x1 = Nd4j.rand(Array(3, 2))
  val x2 = Nd4j.ones(3, 2)
  println("x1 data hash is: " + x1.data().##)
  println("x2 data hash is: " + x1.data().##)

output:
x1 data hash is: 263885709
x2 data hash is: 263885709
It seems x1 and x2 share a same dataBuffer

**Comment by raver119** [comment]
Not a bug. 
DataBuffer isn't following regular java convention for equalsTo/hashCode. It's also has slightly different uses in nd4j-native/nd4j-cuda backends.

This is done to make people never work on DataBuffer level, never ever use it as key or unique value and so on. Since we don't support native operations on buffer level, ever hashCode()/equalsTo() call would be a performance disaster.

**Comment by Charele** [comment]
@raver119 
I know it's not a bug.
I just want to know when(or which) will use this custom hashCode()?
