### ISSUE TITLE
ND4J/Libnd4j/SameDiff: Remove custom op calculateOutputShape implementations

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7901]
We should have only one implementation (in c++).
Either the java implementation matches c++ shape function, and hence is redundant.
Or, it's different to c++ - which is also bad.

**Comment by rnett** [comment]
Questionable ones:
`Broadcast`: where is the c++ op?  `broadcast_dynamic_shape` seems like a different op, has different shape function.
`Enter`, `Exit`, `LoopCond`, `Merge`, `NextIteration`, `Switch`: are there c++ ops?  Should probably use shape inference rather than checking for input variable's arrays.
`GradientBackwardsMarker`: no c++ op?
`HashCode`: No shape function in c++.
`Identity`: No shape function in c++.
`Linear`: no c++ op?  Defined `exec`.  Can we deprecate and replace with `XwPlusB`?
`NoOp`: No c++ shape function.
`TensorArraySize`: where is the c++ op?
`TensorMMul`: no transpose used in c++ calcs?

`Cast`: no handling of extra or empty bits in c++ (that I can see), has extra handling for them Java side.  Placeholder shapes too, possibility.

`BaseArithmeticBackpropOp`: Same as `DynamicCustomOp` (calls c++) but w/o error checks, is this intentional?
`BaseDynamicTransformOp`: calls c++ if there are 2 args, otherwise has its own logic (move to c++?).
`BaseTensorOp`: emptyList, b/c its unused.  Still move to c++?

`EqualTo`: special cases around c++ call.
`Eye`: sets the data type of the c++ shape.
`GreaterThan`, `GreaterThanOrEqual`, `LessThan`, `LessThanOrEqual`: special cases around c++ call.
`Linspace`: special case around c++.
`NotEqual`: special case of c++.
`Tile`: special case around c++ call.

A lot of these have basic handling (mostly null checks) wrapped around a c++ call, can we skip those?

For example, all of the comparison ops look like:
```java
@Override
public List<LongShapeDescriptor> calculateOutputShape() {
    if (args() == null)
        return Collections.emptyList();

    if (inputArguments.size() == 0)
        return Collections.emptyList();


    return Nd4j.getExecutioner().calculateOutputShape(this);
}
```

Also, ops like `less` don't have a shape function, but use `BROADCASTABLE_OP_IMPL`, does that auto generate shape functions or something?

**Comment by AlexDBlack** [comment]
@rnett Yeah, we'll only worry about DynamicCustomOp only for now

Broadcast: it's unused, looks wrong. Delete whole class.

Enter, Exit, LoopCond, etc - these aren't "real" ops in the sense that they just signify what the graph execution code should do. Maybe let's just throw an unsupported operation exception in them... that *should* be fine here and clarify what's going on.
Ditto for GradientBackwardsMarker, TensorArraySize / BaseTensorOp

HashCode, Identity, NoOp: they are inherited (note the template types - REDUCTION_OP_IMPL and OP_IMPL - they are defined in superclasses)

Linear: Let's remove it, along with Module interface and BaseModule. It's not maintained, won't work at present (or beta4).

TensorMMul: Open an issue and flag this for review, there's a few things there that aren't right (like TF import name is wrong - should be "MatMul" which already maps to Mmul op)

Cast: empty/extra should be fine in C++ at first glance. Remove and test correctness.

BaseArithmeticBackpropOp / BaseDynamicTransformOp: Remove and see what fails. I don't like this special handling here...

EqualTo: remove special case

Eye: Need to add dtype arg to c++ op

GreaterThan etc, Linspace, NotEqualTo, Tile - remove

**Comment by rnett** [comment]
Everything here has been done except Eye and TensorMmul (possibly) pending https://github.com/SkymindIO/deeplearning4j/pull/193 and NoOp pending #8131.
