### ISSUE TITLE
SameDiff weight init is not deterministic

### ISSUE THREAD

**Issue by orausch** [deeplearning4j/deeplearning4j#8248]
#### Issue Description
The following test fails:
```
    @Test
    public void testSamediff() {

      SameDiff sd0 = SameDiff.create();
      SameDiff sd1 = SameDiff.create();
      Nd4j.getRandom().setSeed(0);

      SDVariable rand0 = sd0.var("random", new UniformInitScheme('c', 3), DataType.FLOAT, 3, 1);

      Nd4j.getRandom().setSeed(0);
      SDVariable rand1 = sd1.var("random", new UniformInitScheme('c', 3), DataType.FLOAT, 3, 1);


      Nd4j.getRandom().setSeed(0);
      System.out.println(rand0.eval());

      Nd4j.getRandom().setSeed(0);
      System.out.println(rand1.eval());

      assertTrue(rand0.eval().equalsWithEps( rand1.eval() , 0.0001));
    }

```

#### Version Information

* Deeplearning4j version: `beta5`
* Platform information: `Ubuntu 18.04.3 LTS`

**Comment by AlexDBlack** [comment]
Thanks for reporting this. Fixed here: https://github.com/KonduitAI/deeplearning4j/pull/12
This will be merged back to the Eclipse repo shortly, and the fix will be available on snapshots some time next week.

**Comment by orausch** [comment]
Will you backport this to beta5? If not, is there another release upcoming that fixes this?

**Comment by AlexDBlack** [comment]
It's not possible to backport fixes to a past release (and keep the same version name, anyway).
We expect that there will be a new release soon (next few weeks).

Also new snapshots will be available some time this week, that will include the fix: https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots
snapshots are not being built at present but that will be fixed in the next few days
keep an eye on the timestamps here, or ask in gitter if you want an update - https://gitter.im/deeplearning4j/deeplearning4j
https://oss.sonatype.org/content/repositories/snapshots/org/deeplearning4j/
