### ISSUE TITLE
libnd4j: bias_add polishing

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#8556]
libnd4j bias_add op needs some love on CPU:

1. Right now there's only one universal loop for both NCHW and NHWC cases, which is not good for performance. We need both loops optimized.

2. This op might be manyally optimized for target archs: SSE, AVX2, AVX512 for both NCHW and NHWC cases. Plus we should leave some space for future NEON optimization.

**Comment by quickwritereader** [comment]
this issue is still in progress as several helper experiments are conducted on this.
Here is the current state from the latest commit:

Bias Add Optimizations: [[Experimental]]

Channel at the end case:
+ Vectorized continuous case for C and Fortran order
+ Vectorized and ordinary case for the same strided and same orders
+ generic case
+ Operations to flatten bias for smaller cases

Channel at the 1st index case:
+ Vectorized and ordinary case for the same strided and same orders
+ generic case
- [[missing]] for smaller n*c case there is possibility to flatten n*c to benefit from vectorization.
In that case we have to use streamed inner bias operations instead of broadcasted scalar bias

Helpers:
+ parallel threading calls that can preserve dimension with fair partitioning
+ fast offset and index calculations helpers.
 + Loop fusing with multi_radix increment.
 + Multi radix addition
 + Proper C and fortran order index to coords.
- [[optional]] NdArray iterator or range helpers that can use multi-radix increment and comparison using the total size
  We gonna use index and  size  for handling loop condition, as using multi-radix comparison is not fast 

Test and Benches:
+ test coverage for the main cases
- [[missing]] full test coverage for all cases ,in place op and etc
+ benchmarks for rank 4 and equality check

Vectorization Simd:
+ [[info]] -march=native -mtune=native flags yield better simd instructions
+ C define style simd operation example (only avx2)
+ C++ vector template simd example (only avx2)
+ testing the autovectorization function

**Comment by raver119** [comment]
Implemented and merged quite some time ago.
