### ISSUE TITLE
deeplearning4j-core - Trojan warning in its Java dependencies

### ISSUE THREAD

**Issue by george-toma** [deeplearning4j/deeplearning4j#8612]
Hi folks,

Windows Defender antivirus shows a trojan in one of the transitive dependencies from deeplearning4j-core/examples package/project and to be more specific in opencv for MacOS.

By default when you compile the project all OS dependencies are downloaded from the central Maven repository, so everyone has this trojan in their machines.

In case this is not a false alarm of Windows Defender, you should consider notifying the users of this framework and address this security issue.

Also, maybe a security check step before publication to mvn repository should take place.

Details :
- dl4j version used 
```
<dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>1.0.0-beta4</version>
  </dependency>
```
- from where it comes the trojan 
`org\bytedeco\opencv\4.0.1-1.5\opencv-4.0.1-1.5-macosx-x86_64.jar`
- trojan name - **Trojan:MacOS/Lightaidra**
- Log from Windows Defender 
file:C:\Users\user\.m2\repository\org\bytedeco\opencv\4.0.1-1.5\opencv-4.0.1-1.5-macosx-x86_64.jar->org/bytedeco/opencv/macosx-x86_64/libopencv_dnn.4.0.dylib

Based on Microsoft this trojan is used for DDoS attacks and to establish IRC communication with "villain users".

I had to remove my personal Java projects from this framework.

**Note** I did not check any newer version, but there is a high chance of this being present even on newer versions.

**Comment by raver119** [comment]
That’s kind of strange, since we all have defender on windows machines. So we should have been notified loooong before binary gets into release repo.

So I doubt that’s the case, but we should check that.


Can you please provide use with sha256 hash of the jar file?

With best regards,
raver119
12 янв. 2020 г., 17:57 +0800, george-toma <notifications@github.com>, писал:

**Comment by george-toma** [comment]
Hi Raver119,

Thanks for the quick response.

Maven sha1 is f5ba57e5c0999cece8bc7171f639d876abab5ff6.

By default, I don't believe Windows Defender scans inside archives files and it does this only when a manual scan is started.

I scanned with Kaspersky and Avast and I got no warning, so this might be a false alarm of Windows Defender.

Thanks,

**Comment by AlexDBlack** [comment]
I didn't realize this issue was still open until now.
I've run both the JAR and the .dylib file (extracted from the JAR) through virustotal.com
Microsoft is the only one (out of 59 total) that is flagging this. Given that, I'm going to close this as a false positive.

You can see the summary results here, or run it yourself to confirm.
[Scan_1.pdf](https://github.com/eclipse/deeplearning4j/files/4142091/Scan_1.pdf)
[Scan_2.pdf](https://github.com/eclipse/deeplearning4j/files/4142092/Scan_2.pdf)
