### ISSUE TITLE
Nd4j.rand generates random numbers [0, 1]. convention is [0, 1)

### ISSUE THREAD

**Issue by RobAltena** [deeplearning4j/deeplearning4j#8800]
#### Issue Description
Nd4j,rand generates random numbers in the interval [0, 1]. However convention in Numpy and other programing languages is to use [0, 1) excluding 1.9. This will cause problems porting code to Nd4j.

Unit test to show the behavior:

    @Test
     void testRandomOne() {
        while (true){
            INDArray max = Nd4j.rand(1000).max();// expect [0 - 1).
            if (max.getDouble(0) >= 1.0){
                System.out.println(max.getDouble(0)); // but eventually we get a 1.0
                Assert.isTrue(false);
            }
        }
     }

This test should loop indefinitely. Nd4j eventually generates a 1.0 and fails the test.

Here is documentation from other languages to show that [0, 1) is convention:

**Numpy:**  
https://numpy.org/doc/1.18/reference/generated/numpy.matlib.rand.html?highlight=rand#numpy.matlib.rand

**Java:**
https://docs.oracle.com/javase/8/docs/api/java/util/Random.html#nextDouble--

**C++:**
https://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution

**Comment by treo** [comment]
This affects RL4J, as it uses a random value here: https://github.com/eclipse/deeplearning4j/blob/master/rl4j/rl4j-core/src/main/java/org/deeplearning4j/rl4j/policy/ACPolicy.java#L80-L86

I'm aware that it can be worked around with `<=` instead of `<` in this case, but breaking the generally valid assumption that the number never is going to be exactly 1 makes bugs like this hard to spot.

**Comment by treo** [comment]
This is fixed now. After 15 minute loop of trying to get 1.0 out of the random number generator and more than 40 million random numbers, 1.0 didn't happen even once, while before it would usually be encountered even before 1 million random numbers have been drawn.
