### ISSUE TITLE
CI: Intermittent JVM crash on TestVertxUIMultiSession.testUIMultiSessionParallelTraining

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8891]
Not reproducible locally in 25 runs (Windows, CPU)

https://jenkins.konduit.ai/blue/organizations/jenkins/konduitai%2Fdeeplearning4j/detail/PR-347/3/pipeline/702

Copy of logs:
[20200428_CI_jvm_crash_log.txt](https://github.com/eclipse/deeplearning4j/files/4543375/20200428_CI_jvm_crash_log.txt)

**Comment by printomi** [comment]
I managed to crash this test on my Windows 10 PC, Java 8u241. Here are some logs:
https://gist.github.com/printomi/b004a345a4b708037a38ba04d4cf8173
- The first log dates back to 14th April.
- The console output and the next log file (hs_err_pid8428.log) is the latest run.

Steps to reproduce:
- I haven't run `maven -U install` recently (for 2 days).
- In IntelliJ, I opened deeplearning4j-vertx.
- I checked out my development branch [printomi:ui_multisession_arbiter](https://github.com/printomi/deeplearning4j/tree/ui_multisession_arbiter).
- I pressed "Reimport all Maven Projects" in IntelliJ. This used to update dependencies, but maybe, not snapshots.
- I ran separately `testUIMultiSessionParallelTraining()`.

I haven't dealt with this crash issue, because crashes used to disappear after a `maven -U install`.
So I ran `maven -U install`, and it helped: **the test now passes**.

**Comment by printomi** [comment]
The test passed for me again, without any crash. I guess that the crash depends on how you run the test. In my previous comment, I wrote the steps how I previously made this test crash. Maybe, inconsistently updated dependencies can be the cause.
