### ISSUE TITLE
How to setInputType(NCHW) for KerasModel?

### ISSUE THREAD

**Issue by thammegowda** [deeplearning4j/deeplearning4j#9017]
#### Issue Description

We are using Kera model in [Apache Tika](https://github.com/apache/tika/blob/233a72d45de515a7ecb5988802559690cd91f57a/tika-dl/src/main/java/org/apache/tika/dl/imagerec/DL4JInceptionV3Net.java#L261-L264) as

```java
KerasModelBuilder builder = new KerasModel().modelBuilder()
             .modelHdf5Filename(modelWeightsPath)
            .enforceTrainingConfig(false);
builder.inputShape(new int[]{imgHeight, imgWidth, 3});
KerasModel model = builder.buildModel();
```
The model weights are here: https://github.com/USCDataScience/tika-dockers/releases/download/v0.2/inception_v3_keras_2.h5 
It was working fine earlier but after the recent upgrade to `1.0.0-beta7`, we get an error.

(extracted from debugger on Pycharm)
`
org.deeplearning4j.exception.DL4JInvalidInputException:
  Cannot do forward pass in Convolution layer (layer name = conv2d_1, layer index = 1):
  input array channels does not match CNN layer configuration (data format = NHWC, data input channels = 299, [minibatch, height, width, channels]=[1, 3, 299, 299]; 
  expected input channels = 3) (layer name: conv2d_1, layer index: 1, layer type: ConvolutionLayer)
  Note: Convolution layers can be configured for either NCHW (channels first) or NHWC (channels last) format for input images and activations.
  Layers can be configured using .dataFormat(CNN2DFormat.NCHW/NHWC) when constructing the layer, or for the entire net using .setInputType(InputType.convolutional(height,  width, depth, CNN2DForman.NCHW/NHWC)).
ImageRecordReader and NativeImageLoader can also be configured to load image data in either NCHW or NHWC format which must match the network
`

Could you please help us fix this error? 
There should be some way to explicitly set 
`.setInputType(InputType.convolutional(... CNN2DForman.NCHW));`

But we are unable to find it or get it work.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: `1.0.0-beta7`
* Platform information : OSX 10.15.5 
* CUDA version, N/A
* NVIDIA driver version, N/A

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace: [See this Jira issue](https://issues.apache.org/jira/browse/TIKA-3119?focusedCommentId=17140962&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17140962)
* pom.xml file or similar: https://github.com/apache/tika/blob/233a72d45de515a7ecb5988802559690cd91f57a/tika-dl/pom.xml

**Comment by treo** [comment]
>There should be some way to explicitly set
>.setInputType(InputType.convolutional(... CNN2DForman.NCHW));

Originally we we supported only NCHW and tried to convert Keras models to that format. However, it resulted in many edge cases and layers upon layers of workarounds. 

For this reason we have decided to cut the workarounds, and instead import models the way the are originally defined.

But this in turn means that you can not configure how the model is supposed to be imported.

There are two things you can do here:
1. **Convert the Keras Model to a DL4J Model in beta6.**  If you say that you were fine with the way things worked in prior versions, you can convert the model file to a DL4J model in beta6 and then just load it in beta7. Converting a Keras model to a DL4J model is as simple as importing that model and then saving it.
2. **Update the way you are preparing the input**.  The recommended way of handling this situation is to update the way you are loading your input such that it conforms to what the model expects.  If using an ImageRecordReader it can be configured to do that for you, if not, you can do what it does yourself: `array = array.permute(0,2,3,1);`  (see:
https://github.com/eclipse/deeplearning4j/blob/master/datavec/datavec-data/datavec-data-image/src/main/java/org/datavec/image/recordreader/BaseImageRecordReader.java#L249-L251)

It appears something like the second option was tried in that Jira thread, but as there aren't many details about what exactly the problem was there, it is hard to give you anything more than this answer.

**Comment by agibsonccc** [comment]
@thammegowda  I'm doing a pass on import issues and wanted to double check on this. Did your team find a work around?

**Comment by thammegowda** [comment]
@treo thanks for the suggestions.

@agibsonccc  thanks for checking this again. we haven't found a workaround.

As suggested above, (1) Conversion of the model using beta6, then upgrading to beta7 is just too much work for Apache Tika end (hosting new model weights, updating the URLs, etc; I am not actively work on Tika or DL4J). 

and (2), I had already tried transposing the input from NCHW -> NHWC, but the JVM crashed with some unintelligible and low-level error

**Comment by agibsonccc** [comment]
@thammegowda  thanks. I'm trying to address this now. Let me look at the test cases and see what I can do.

**Comment by agibsonccc** [comment]
Should be fixed now with snapshots. Look for this in the next release.
