### ISSUE TITLE
dataset.class name with get/set

### ISSUE THREAD

**Issue by cagneymoreau** [deeplearning4j/deeplearning4j#9030]
This is a very simple request.

Could the dataset.class have a name or description field which is a simple string with a get/set?

Right now working with multiple datasets stored as lists requires me to maintain a separate list with names/desc.

How else are people labeling their charts when posting multiple datasets to a chart.

**Comment by treo** [comment]
DataSet is meant to contain a mini-batch. It doesn't make any sense to give it a specific name. 

And it has a facility to store metadata (getExampleMetaData/setExampleMetaData) that is per-example. 

If you need to store some kind of description, why not just use a List of pairs instead of two lists?

**Comment by cagneymoreau** [comment]
I'm really confused about how this api is supposed to work then. Maybe you could clear it up.

Lets say a I create a method that generate two INDArrays representing features and labels. 

I need to run this method some number of times and pass those pairs into a network and later a chart.

Is there an object for encapsulating the data pairs? 


your suggestion regarding the examplemetadata should work though.

**Comment by treo** [comment]
Ideally you aren't building them yourself, and instead use the given API's for data reading. If you need to read custom data it is preferred to create a custom Reader instead of trying to skip all of this and go directly to creating the tensors yourself.

If you insist on doing so, note that they have to have the minibatch size as the leading dimension. 

A `DataSet` object then is composed of up to 5 elements:
1. Features
2. Labels
3. Feature Mask (may be null)
4. Label Mask (may be null)
5. Metadata (may be null)

In most cases people don't care about the meta data though, so it isn't part of its [constructor](https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/DataSet.java#L100-L107).

**Comment by cagneymoreau** [comment]
Thanks for your feedback. dl4j is a great resource as a result of the countless hours invested. The examples and documentation are the weak links for beginners like me.
