### ISSUE TITLE
Need support for new RL algorithms 

### ISSUE THREAD

**Issue by hanbaoan123** [deeplearning4j/deeplearning4j#9065]
There are so many RL algorithms now except DQN and A3C that have been implemented by DL4J, such as double DQN, dueling DQN, DPG, DDPG and so on. It is highly expected that these algorithms will be implemented to expand the application of DL4J.

**Comment by agibsonccc** [comment]
@aboulang2002  has been helping out quite a bit there.

@hanbaoan123 we haven't been putting as many resources in to rl4j. You're welcome to contribue though!
I'm closing this since there's not a concrete action to be made here unless you have a specific algorithm you want implemented. I'll just use this as a way of notifying you who to ping and how to scope an issue.
