### ISSUE TITLE
Spark 3.0 support?

### ISSUE THREAD

**Issue by Freshwood** [deeplearning4j/deeplearning4j#9129]
#### Issue Description

We don't find any information about the latest spark support in the official documentation.
Also the distributed DL4J examples rely on Spark 2.x version. See also the example pom.xml:
https://github.com/eclipse/deeplearning4j-examples/blob/master/dl4j-distributed-training-examples/pom.xml

What is the latest supported Spark + Scala version?

Thank you very much for your help.

**Comment by agibsonccc** [comment]
@Freshwood  still WIP yet. We're evaluating adding support for horovod or something that already solves this problem. The team doesn't really have many use cases for spark at this point. We're looking to add something that's a bit easier to maintain given the focus on inference and application deployment at this point. If you or someone on your team wants to take a look at updating the current spark implementation for spark 3.0, please feel free to let us know and we can review. Otherwise we'll see if we can do a minor pass on what's there and just update the dependencies.
