### ISSUE TITLE
GNN implementation

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#9132]
Is there a plan to implement any GNN ops/layers?

**Comment by SidneyLann** [comment]
How about to implement a GAT?

**Comment by agibsonccc** [comment]
Closing due to this being a bit vague...try to be a bit more specific with which sets of ops you'd be needing. A link to any other framework's implementation would be useful. If any of these things warrant dedicated c++ ops, we'll definitely consider it. If it's more of just creating modules comprised of existing ops, that likely belongs in examples or something else.
