### ISSUE TITLE
[Clarification needed] AdaGrad sum of gradient squares initialized with 1

### ISSUE THREAD

**Issue by dkmisra** [deeplearning4j/deeplearning4j#953]
## Clarification Needed

I see that AdaGrad sum of gradient square is initialized with 1. Seems like it was added to prevent 0/0 form when initial gradients are 0. However, this 1 in the denominator will give wrong results by a significant margin in future steps (a gradient can be order of magnitude smaller). 

Also there is an epsilon addition at every step?

**Comment by AlexDBlack** [comment]
So yes: the motivation was to avoid numerical issues (0/0 -> NaN)
I don't believe there was any strong theoretical motivation for the 1-based initialization. I agree it could be problematic in general (squared gradients could be very small, hence sum of squared gradients could be dominated by initialization).
Perhaps it would be better to simply initialize the adagrad gradients with an epsilon once, rather than at every step.

Should be straightforward to modify, feel free to contribute a pull request for this if you want. :)

Also note that RMSProp may need a review for the same sorts of reasons: https://github.com/deeplearning4j/nd4j/blob/510532dc4b5b63a2f17c1fd5b294e1ec7281cfe2/nd4j-api/src/main/java/org/nd4j/linalg/learning/RmsProp.java

**Comment by nyghtowl** [comment]
Closed with https://github.com/deeplearning4j/nd4j/pull/888
