### ISSUE TITLE
InvalidKerasConfigurationException: Cannot assign arrays: arrays must both be scalars, both vectors, or shapes must be equal other than size 1 dimensions. Attempting to do x.assign(y) with x.shape=[32, 1, 5, 1] and y.shape=[5, 32, 32, 1] Tried to set weights for layer with name conv1d_1, of class org.deeplearning4j.nn.conf.layers.Convolution1DLayer.

### ISSUE THREAD

**Issue by rogerlee24** [deeplearning4j/deeplearning4j#9560]
#### Issue Description
when I am attempting to load a pre-trained Keras model (with TF backend) from python into Dl4j. I encountered the error,I don't know how to solve it.
![image](https://user-images.githubusercontent.com/57137841/144702432-12d96a7c-df5e-4ac0-b07d-e3356fb039b3.png)

it is my model.
[model1.zip](https://github.com/eclipse/deeplearning4j/files/7653579/model1.zip)

can you give me some advices?
Thanks for your patience!
#### Version Information
Dl4j: 1.0.0-M1.1
Nd4j: 1.0.0-M1.1
Python: 3.7
Keras: 2.3.1
Tensorflow (as backend):1.15

**Comment by agibsonccc** [comment]
@rogerlee24 
Here's your converted model. 
This issue is fixed here: https://github.com/eclipse/deeplearning4j/pull/9559
[converted-9560.zip](https://github.com/eclipse/deeplearning4j/files/7654929/converted-9560.zip)

I would suggest waiting for snapshots.  Generally the build for non c++ bits takes around 30 minutes.

I kicked a build off based on my changes just now so it should be fine now. Your model has been added as a test case for us. Thanks for reporting this!
