### ISSUE TITLE
Examples for standard linear algebra operations such and decompositions and solvers

### ISSUE THREAD

**Issue by lessthanoptimal** [deeplearning4j/deeplearning4j#9592]
Request: Clear examples for performing standard linear algebra operations such as matrix multiplication, matrix inverse, SVD, Eigenvalue, matrix inverse, ... etc.

I've been asked by multiple people to add ND4J to [Java Matrix Benchmark ](https://lessthanoptimal.github.io/Java-Matrix-Benchmark/)but have been having issues trying to figure out how to do all the standard operations. See the discussion in [deepleanring4j-examples.](https://github.com/eclipse/deeplearning4j-examples/issues/1003). One requirement for inclusion in the benchmark is that all operations included be documented and targeted at novice users. Basically it should be the easy to use API that anyone can get running right away by cut and pasting example code and not some low level, potentially numerically unstable, code that only the develop can find.

Here's the current work in progress wrapper for [ND4J](https://github.com/lessthanoptimal/Java-Matrix-Benchmark/blob/nd4j/external/nd4j/src/jmbench/nd4j/Nd4JAlgorithmFactory.java).

It now has everything in it but:
* matrix inverse SPD matrices
* matrix determinate
* Eigenvalue decomposition

What's the preferred location to get documentation? When I did a google search I got a bunch of 404 but was able to navigate to https://deeplearning4j.konduit.ai/nd4j/tutorials . If so it could use more flushing out and I'm willing to help with that.

I'm also working on getting the numerical stability benchmark running again. I'll share the results with you when I do. It's found many nasty bugs in multiple libraries in the past.

**Comment by agibsonccc** [comment]
@lessthanoptimal thanks a lot for flagging this. It would be great to get nd4j up to spec with the benchmark. 

Let me start off with some history so you understand why things are the way they are:

To start off we recently removed a lot of older docs that were out of date so as to avoid confusing users. We've also historically had some problems we're still cleaning up with our CMS Gitbook. Apologies for that and thanks for flagging. 

Regarding the tutorials, what would you like to see? Most of our examples for nd4j can be found here: https://github.com/eclipse/deeplearning4j-examples/tree/master/nd4j-ndarray-examples

Reading through your discussion here: https://github.com/eclipse/deeplearning4j-examples/issues/1003

You're hitting issues with an underused part of the library. The main purpose of the library has historically been to just be a wrapper for the c++ library:  https://github.com/eclipse/deeplearning4j/tree/master/libnd4j

You'll see what's more complete and  has more investment is the deep learning part (which is the main purpose of the library with the lapack parts being secondary)

The first integrations with blas/lapack were done so as part of a main focus on adding support for GEMM with the rest being secondary.

Many of the lapack parts of the library were maintained by the community. That's definitely something I agree should be cleaned up and would be happy to do so. As these are just wrappers it shouldn't be that bad.

One reason for the spotty integration was the sparse support for lapack ops in our cuda backend. The way nd4j works is it splits everything in to backends slf4j style.
So in your benchmarks it looks like you were only comparing cpu and not even touching our cuda integration.

Also of note is we actually publish different "spins" of nd4j so depending on what platform you run the benchmark on we publish native binaries for different modes of running compute like avx2/avx512. You can find all of the various combinations we publish for here: https://repo1.maven.org/maven2/org/nd4j/nd4j-native/1.0.0-M1.1/

Do you intend on covering both? That should help with identifying the scope we should address.

**Comment by lessthanoptimal** [comment]
@agibsonccc Thanks for all the background information.

You're right that the benchmark is CPU only. Do you think including a link at the top of the results page explaining the situation and linking to a blog post of yours showing how much faster operations will run on a GPU is a good work around for now? In the future we could potentially add a section with GPU results.

Looks like there are only examples for matrix multiply and elementwise operations. A library needs to implement ([link](https://github.com/lessthanoptimal/Java-Matrix-Benchmark/blob/master/main/src/jmbench/interfaces/RuntimePerformanceFactory.java)) this interface to be included in the benchmark. Below is a list of operations

- Cholesky Decomposition
- LU Decomposition
- SVD
- QR Decomposition
- Eigenvalue for Symmetric matrices
- matrix determinate
- inverse of a square matrix
- inverse of a SPD matrix
- add
- matrix mult
- mult and transpose
- scale
- solve exact
- solve overdetermined
- transpose

For "spins" that might involve another conversation. In the past there has been a requirement that there is a single build script for all platforms. External system dependencies are allowed but must be very well document and easy to install, e.g. you can cut and paste a few "sudo apt install" commands. Requiring the user to rebuild multiple C++ libraries for each architecture was clearly too much and so was manually specifying the CPU cache. If the library can automatically determine the CPU cache without user intervention or being "excessively" slow then great. 

Is there a way to get the correct spin without modifying the build script? Could it just download them all and figure out which one to use a runtime?

**Comment by agibsonccc** [comment]
@lessthanoptimal ok so for our purposes here I'll focus on CPU. I would just add a potential highlight maybe and would appreciate that. 

Let me explain the "spin" part. No one needs to build anything when using nd4j. These jars are provided as is with the binaries automatically working similar in spirit to JBlas or what netlib-java used to do. So let's assume that the benchmark runs a pre specified version . I mention this because even for linux we have different spins to let the user handle the trade off of speed vs compatibility (usually newer compiler features vs running on older say: centos systems).

You are right to interpret these libraries as basically the same java bindings to different ways of compiling the same library however.

Regarding "external dependencies" actually these are not a thing to worry about. We allow the user to pick the BLAS to use as well. This happens by a standard maven dependency include.
Openblas: https://search.maven.org/artifact/org.bytedeco/openblas/0.3.17-1.5.6/jar
MKL: https://search.maven.org/artifact/org.bytedeco/mkl/2021.3-1.5.6/jar
 as example

Of note here though is: if I remember right the benchmark can run on multiple kinds of CPUs. If that's the case then our linux-arm64 integration with armcompute(https://github.com/ARM-software/ComputeLibrary) will matter as well.  If so that is baked in to our arm bindings without needing to specify anything.

Another  classifier we have is linux-x86_64-compat which runs on older glibcs but won't have access to newer compiler features. If the benchmark is standardized maybe we can just pick the best classifier for the benchmark?

These libraries are generally baked in or auto included via standard java workflows in javacpp which we depend on and maintain for binding against any native library you might need to run.

To have the best benchmark if I can understand it a bit better we can suggest the right BLAS library and setup with the best trade offs with maybe a note explaining that there are different options if people want that. Then from there, with your input I would like to maybe document this better.

Whatever we decide to do here I'd be happy to help with the script as well.

When you say "build script" could you point me at what you're referring to? From there I could look at a way of including this. My basic idea here  would be to ideally help you setup a pom.xml that could sort of auto configure the right dependency. That's usually a mechanism similar to this:
https://github.com/eclipse/deeplearning4j/blob/master/pom.xml#L1142

Regarding your last question on the downloads more or less yes as described above. I would probably suggest a maven profile + set of deps that triggers a backend automatically depending on the system present that equates to the highest performance. That should allow us to achieve an object benchmark where we put our best foot forward without compromising ease of use at least for the benchmark.

From there I can  ensure there's an easier interface for you to work with from there. Let me get back to you on the end to end approach for running all these various ops after I understand how we want to configure this. Then we can both pre setup the concrete BLAS/Lapack to use as well as ensuring that the right BLAS/Lapack combinations are tested.

**Comment by agibsonccc** [comment]
@lessthanoptimal any updates here? Would appreciate some input. I am going to spend some time before our release (within the next week or 2) auditing our blas/lapack support.

**Comment by lessthanoptimal** [comment]
Sorry for taking so long to reply! I got pulled away on some other tasks and did a poor job mode switching.

I think the easiest way to handle this is to pick one set jars from bytedeco for x86, arm32  (Raspberry PI), and arm64 and just include them always in the dependencies. At runtime the correct architecture is loaded so the only downside is bloat, which doesn't matter. To date we have not differentiated between architectures at a more fine grained level, i.e. include ops for "newer" chips. The reason for that is the average user really just cuts and pastes the first example they see without reading the actual documentation. I'm not sure where a  good cut off would be, maybe assume the CPU was build in the past 10 years and the OS is up to date as in the past 4?

Gradle is used to build the benchmark project and all java dependencies. External .so files were loaded by running a bash script that just made "apt install" commands.

The build process for the benchmark should be similar to the most simplistic instructions you would provide a new user on the web. From personal experience, if you have a complex flow diagram for which dependency is optimal for which architecture you're going to have a lot of confused users. I tend to tackle that problem by saying "install this first" then go to this page if you want to get up to X% faster performance.

**Comment by lessthanoptimal** [comment]
As a side note, the memory and numerical stability benchmarks are up and running again. Those should be a good way to validate the correctness of dl4j.

**Comment by agibsonccc** [comment]
@lessthanoptimal We sort of do that using nd4j-native-platform. That will include all the dependencies you need out of the box. Having too many different maven artifacts as "spins" will just be even more confusing to users though.

Beyond that, binary size (especially on android and embedded scenarios like pis) are actually a big problem. We can't just include everything wholesale. So the compromise is what I described above there.

Most java libraries today aren't performant or conscious of modern standards for running math workloads. A good example back in the day was netlib-java and jblas. Both store data on the java heap which isn't practical. You always have copy data over to offheap to even see basic performance gains. I know nd4j is a wildly different animal from the rest of the libraries in your list there so I'd like to get your input on the best way to handle it.

From what I'm seeing if we have nd4j-native-platform that will provide the defaults for you.

So I guess the next question...what glibc compatibility should we aim for in the benchmarks? We build on ubuntu 18.04 (read: not centos 7) for some of our builds and this has been a problem for some users. We provide a compat module for that use case but that is not included in nd4j-native-platform. I guess as long as we can nail that I guess we'll use openblas as the base BLAS/Lapack implementation and something relatively recent for defaults which should at least get us close to an out of the box experience for the users.

**Comment by agibsonccc** [comment]
@lessthanoptimal I finally got to this. Basically we have a pre generated DSL for ndarrays that follows a namespace format similar to our sameiff library. It'll be 1 uniform interface with Nd4j.linalg() - do you want to see anything else here? I had to spruce up a few of our existing ops and add some missing bindings but overall the code is already there for it  just wasn't exposed properly.

Are you ok if I just implement what's in your benchmark spec and then maybe add a docs page for this?

**Comment by lessthanoptimal** [comment]
@agibsonccc I'm fine with you implementation it yourself, would actually prefer that. I will double check that you don't use any undocumented or advanced capabilities that the "average" user won't use. So basically it needs to be documented and to the point that someone could simply cut and paste your code.

Also sorry for taking a while to reply. I probably won't be very consistent at replying for a bit. Trying to get a new company started right now.

**Comment by agibsonccc** [comment]
@lessthanoptimal don't worry about it! I don't need instant prioritization. We'll both get to this as we have time. I just wanted you to know that there's at least a way to do it. I'll see if I can update your benchmarks in the mean time.
