### ISSUE TITLE
Python4J Performance Optimizations

### ISSUE THREAD

**Issue by subes** [deeplearning4j/deeplearning4j#9595]
Hi,

I took a go at Python4J and compared it to some other integrations: https://github.com/invesdwin/invesdwin-context-python/blob/master/README.md#results

Following findings:
- PythonGIL should be made reusable: https://github.com/cnuernber/libjulia-clj/issues/4#issuecomment-1008055456
- type conversions can be made a lot faster and a None/Null type could be supported: https://github.com/cnuernber/libjulia-clj/issues/4#issuecomment-1008125477
  - don't call PythonObject.isNone() because it is very slow
  - I could not find a way to create a new "None" instance, thus I used a workaround to get a new one allocated from the python side, though this is only relevant when lists have "null" elements. I guess there should be a better way to do this directly via CPython API.

With the new implementation of PythonTypes I was able to get it from ~7k calls per second to more than 100k calls per second.
See implementation here (especially the ModifiedPythonTypes class): https://github.com/invesdwin/invesdwin-context-python/tree/master/invesdwin-context-python-parent/invesdwin-context-python-runtime-python4j/src/main/java/de/invesdwin/context/python/runtime/python4j/internal

![grafik](https://user-images.githubusercontent.com/332937/148657965-9d376dd0-c734-4643-9a1b-fdf54c9b367e.png)

**Comment by agibsonccc** [comment]
@subes looking closer at this if you want, we'd be happy to accept a pull request for this. Your changes look great!

**Comment by agibsonccc** [comment]
Looking at the licensing it's impossible to integrate this work. I'll think on this a bit in the future and clean this up but I will have to do this clean room and basically ignore the ideas presented here as is. I appreciate the contribution though! A follow up with the proper license to contribute the changes back would have gone a long way. Sorry it didn't work out but I assume the lack of activity here means it's not really worth your time.

That being said some of the ideas here are definitely worth looking further in to in a clean context.

**Comment by subes** [comment]
Why? Can"t I just give you the permission to use this under a differing license? Which I hereby grant.

**Comment by agibsonccc** [comment]
Appreciated then.  Could I get your confirmation for apache license? Sorry
just paper trail for eclipse foundation :)

**Comment by subes** [comment]
Yes, apache license is fine. I will upgrade to the new version of Python4J as soon as the improvements are included.

**Comment by agibsonccc** [comment]
@subes how would you expect this to work with your library? I spent a good portion of today looking through your implementation. Would you want us to just implement the internals part? There's a good part of the threading infrastructure that might need to be separated in order to make it work properly with either your library or other server applications. I'd appreciate some insight in to your expectations here.

Some of the things you have in your tools (netty, guava,..) make it a bit harder for people to depend on due to clashes in their dependencies. Thanks to that I started with shading netty-util to benefit from the threadlocal implementation there. We already had guava so it wasn't hard to get that in there.

I appreciate you doing what you did. I hope we can make some of the changes you did here upstream useful to you. Thanks!

Edit: You may find the work in progress here: https://github.com/eclipse/deeplearning4j/pull/9688 I'm still playing with some of the concepts yet so pardon the mess. 

One thing I'm trying to avoid is over complicating the implementation. I also want to avoid some of the traps we fell in to before. We had actually attempted a thread pool managed interpreter architecture before but that ended up being buggy.

**Comment by subes** [comment]
I don't think you need to port everything into there. The thread handling can stay on my side. I think porting the data conversion improvements and allowing reuse of a GilLock instance are the main important points. The idea would be to remove the parts where I had to copy and modify your existing code. The rest can stay on my side.

So an idea would be:
- Integrate something like my GilLock, ModifiedPythonTypes, NonePythonType into python4j (which include the main performance optimisations), so that I can get rid of those implementations on my side.
- We can keep the EngineWrappers on my side which use your low level API (including the context handling and isolation). Though you are free to also adapt that if you want (to maybe create a high level API similar to the "Jep" class of jep). I will just check then later how much I can reuse of that.

Another improvement I can think of would be:
- Remove the need to instantiate PythonObject instances for every round trip, instead use static functions for mappings to remove garbage collector overhead (similar to how other bindings do this by adopting zero copy and zero allocation techniques).

Let me know when there is a snapshot version available that I can integrate against. I will do another performance test with that version then.

**Comment by agibsonccc** [comment]
@subes thanks a lot. I'll have to have some sort of thread management on our side still but will separate that out to make it embeddable. We use this in one of our products (but don't have the performance requirements since the original use case was just to run 1 off scripts) 

I'm definitely ok with removing the overhead where possible hence me looking at how to reuse what's good but benefit from some of the ideas you proposed.

Principally this is used to shift in memory numpy  arrays and opencv objects between python and our equivalent data structures for use in sever environments. As long as we fulfill that use case we're largely good. There's zero reason not to make this a properly optimized integration though.

**Comment by subes** [comment]
I like this library because it comes with an embedded distribution of python. Other integrations all require a separate installation and some even need additional python libraries installed via pip. So the zero configuration you provide is really cool! Jython ist just not an alternative for that because it only supports Python 2 and is horribly slow. :D

So if we can reduce the overhead of this integration, it could become the preferred solution for most use cases.

**Comment by agibsonccc** [comment]
@subes yeah for sure. The goal is to have zero overhead in working with different python libraries and add an easy wrapper on top of cython itself. We could easily add arrow integration as well. Zero reason not to make this library super fast. I appreciate your enthusiasm and support in helping make this happen!

**Comment by subes** [comment]
I had a quick look at the changes. Two things I noticed:

- PythonTypes still inializes an array of types for each conversion, this was one of the biggest performance bottlenecks that I removed in my version by introducing static fields for these (they are immutable anyhow)
- UncheckedPythonInterpreter should not store retrieved variables in a map always. First this introduces a memory leak because the map has no eviction, second this slows down the path for retrievals where caching is not needed. Would be better if a CachedPythonInterpreter (as a wrapper delegate) is introduced as a separate class to opt-in to caching or to leave the caching in the hands of client that calls the interpreter. Creating an entry in the map and creating a Pair object is also garbage collector overhead (further away from zero-allocation principles). Also dunno if it is thread-safe to share variable instances between interpreters because the ConcurrentHashMap is static instead of inside the ThreadLocal.

@agibsonccc ~~In my opinion this issue should be reopened.~~ -> I opened a follow up ticket: https://github.com/eclipse/deeplearning4j/issues/9712
