### ISSUE TITLE
Add a machine learning datasets/repositories section to website

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#976]
Users may find it helpful to have a list of machine learning data sets / repositories on the DL4J website
For example:

http://mldata.org/
http://www.kdnuggets.com/datasets/index.html
http://www.datasciencecentral.com/profiles/blogs/big-data-sets-available-for-free
http://www.datasciencecentral.com/profiles/blogs/great-sensor-datasets-to-prepare-your-next-career-move-in-iot-int
http://socialcomputing.asu.edu/pages/datasets
http://www.datasciencecentral.com/profiles/blogs/20-free-big-data-sources-everyone-should-check-out
http://archive.ics.uci.edu/ml/datasets.html
https://networkdata.ics.uci.edu/browse.php
http://www.networkrepository.com/
https://datamarket.com/data/

**Comment by Cryddit** [comment]
One problem is that hosting decent datasets requires enormous bandwidth and storage.  It could be mitigated to some extent by making torrents of them and providing bittorrent magnet links. 

Another approach is procedural data sets.  You could easily host example-generating code.  I have a small executable that will create as many examples as I want of a particular kind of image like these, with accompanying labels. They can be made any resolution of course.  These are PNGs but the raw output is BMP - much easier to parse.  

![test1258](https://cloud.githubusercontent.com/assets/5466806/14774423/e3f97230-0a6a-11e6-94ae-4caecb228e9a.png)
![test1259](https://cloud.githubusercontent.com/assets/5466806/14774424/e3fdbd68-0a6a-11e6-8d3e-0c3b41a96b6e.png)
![test1260](https://cloud.githubusercontent.com/assets/5466806/14774425/e400349e-0a6a-11e6-83fa-3d9185ade742.png)
![test1261](https://cloud.githubusercontent.com/assets/5466806/14774426/e4031a9c-0a6a-11e6-9f1b-9936d4cc4a56.png)

Anyway, I train a network to extract "simple" information from these pix - how big is each shape (including parts of it unseen due to being "under" other shapes), how they are stacked from bottom to top, etc.  

A network that's been trained to extract information from these toy problems has the correct structure in its deep layers to "see" and is a good starting point for training things that are supposed to read images of any kind.  

Would anyone like me to upload that program? Warning, it's in C not Java. But it's very simple.
