### ISSUE TITLE
Support using ParallelInference to get the output of an internal layer

### ISSUE THREAD

**Issue by mdavis95** [deeplearning4j/deeplearning4j#9841]
#### Issue Description

Currently I am relying on the method 
```
public INDArray[] output(List<String> layers, boolean train, INDArray[] features, INDArray[] featureMasks)
```

to get the outputs of internal `ComputationGraph` layers.

I would like to use the `ParallelInference` wrapper but it does not support that method.

Reference to community post (https://community.konduit.ai/t/using-parallelinference-to-get-a-specific-layer/2054)

#### Version Information

* Deeplearning4j version 1.0.0-M2.1
* Platform information - Arch Linux
* CPU Only

**Comment by agibsonccc** [comment]
@mdavis95 I looked at this and it would require some trade offs...let me know what you'd expect:
 ParalelInference has built in batching. We accumulate inputs over time and then execute once we have enough of a certain batch size.

For your use case are you ok if the layers are fixed? (eg: specify the layers you want on the builder?)

It's not really possible to implement this where you'd just specify it in the output(List<String> without some trade offs.

Either you specify it once in the builder or in the method. After that we'd have to throw an exception if anything else is specified.


I can see the main use case here being just thread safe access to neural networks. If that's the case this shouldn't be an issue. Otherwise I'd recommend using the Transferlearning api to remove layers and then pass that to parallelinference instead.

**Comment by mdavis95** [comment]
In my use case, the outputs I am asking for are always the same for parallel inference.

**Comment by agibsonccc** [comment]
@mdavis95 sorry this took a bit.  I need to do 1 more test yet but most of it should be there: https://github.com/deeplearning4j/deeplearning4j/pull/9855 thanks for the discussion!
